Feature/225 69 component link
KomAnw/whynot pull request #12
Opened 2023-02-07 22:42 UTC by efes2002

### Какую задачу решаем

Создание компоненты Link

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-02-07 22:57 UTC, KomAnw requested changes

2023-02-07 22:57 UTC, KomAnw commented on packages/client/src/design/LinkText.tsx
> +import styled from 'styled-components';
Этот файл нам не нужен, потому что Link сам по себе будет компонентой

2023-02-07 22:57 UTC, KomAnw commented on packages/client/src/components/LinkComponent/LinkComponent.tsx
> +const LinkContainer = styled(LinkText)<LinkStyleProps>`
Я предлагаю отнаследоваться тут от Link, тогда у тебя не будет надобности в контейнере

2023-02-07 22:57 UTC, KomAnw commented on packages/client/src/components/LinkComponent/LinkComponent.tsx
> +  ${props => props.fontSizeText && css`font-size: ${(props:LinkStyleProps)  => props.fontSizeText};`}
Если ссылки у нас могут быть разного размера, то давай сделаем в компоненте проп variant, который будет отрисовывать нужный размер, без прокидывания пропсов fontSizeText и lineHeightText

2023-02-07 22:57 UTC, KomAnw commented on packages/client/src/pages/Welcome/Welcome.tsx
> +      <LinkComponent linkToValue='/game' linkToText='перейти в игру' style={{
Должно получиться как-то так:
```suggestion
      <Link url='someUrl.com' variant='small'>Это ссылка</Link>
```

2023-02-08 15:21 UTC, MikhailSamigullin approved these changes

2023-02-08 20:46 UTC, Kosurij requested changes

2023-02-08 20:46 UTC, Kosurij commented on packages/client/src/components/Link/Link.tsx
> +      return { fontSize: '20px', lineHeight: '27px' };
У тебя small и default абсолютно идентичны. 
Можешь заменить это на объект 

```
const styleProps = {
  small: { fontSize: '20px', lineHeight: '27px' },
  default: { fontSize: '40px', lineHeight: '47px' },
  large: { fontSize: '50px', lineHeight: '57px' },
};
```

2023-02-08 20:46 UTC, Kosurij commented on packages/client/src/components/Link/Link.tsx
> +    <StyledLink {...styleProps} to={url}>
А тут `<StyledLink {...styleProps[variant]} to={url}>`

2023-02-08 20:46 UTC, Kosurij commented on packages/client/src/components/Link/Link.tsx
> +function Link({ children, url, variant }: propsLink) {
А тут нужно будет поправить так `function Link({ children, url, variant='default' }: propsLink) {`

2023-02-08 20:46 UTC, Kosurij commented on packages/client/src/components/Link/type.ts
> +export type sizeType = 'small' | 'regular' | 'large';
`regular` лучше заменить на `default`, т.к. тут подразумевается обычное состояние (дефолтное), когда оно не small и не large

2023-02-08 20:46 UTC, Kosurij commented on packages/client/src/components/Link/type.ts
> +  children: string
children лучше типизировать как `ReactNode`, т.к. сюда могут передать и jsx.element

2023-02-08 20:46 UTC, Kosurij commented on packages/client/src/components/Link/Link.tsx
> +  font-size: ${props => props.fontSize};
Ты же устанавливаешь уже готовые стили. Вроде тут не нужны стили.

@KomAnw Подскажи плиз

2023-02-08 23:40 UTC, KomAnw commented on packages/client/src/components/Link/Link.tsx
> +  font-size: ${props => props.fontSize};
Ну он до этого ссылку пробрасывал, в целом было правильно

2023-02-08 23:42 UTC, KomAnw commented
Я чутка подправил стилистику, а так в целом было ок

2023-02-08 23:42 UTC, merged