change 500 page
KomAnw/whynot pull request #13
Opened 2023-02-08 12:50 UTC by MikhailSamigullin

### Создание страницы с ошибкой 500 с роутом

- Добавлен роут на страницу
- Добавлен роут со страницы на главную (welcome page)
- В константы добавлен новый роут

### Скриншоты
![Screenshot from 2023-02-07 23-10-19](https://user-images.githubusercontent.com/109307026/217344132-d3843f4e-aeda-47a7-9c1f-e60a26f520ed.png)
![Screenshot from 2023-02-07 23-09-44](https://user-images.githubusercontent.com/109307026/217344135-55adddb2-4ff0-46a1-a336-78e7bcfb3513.png)
![Screenshot from 2023-02-07 23-09-34](https://user-images.githubusercontent.com/109307026/217344137-18cc0f6f-e3c8-4a3e-81e0-8ef40672ebc4.png)

### Сделать:

- Обновить кастомный компонент Link на стандартный, после его создания.

2023-02-08 20:50 UTC, Kosurij commented
Мб стоит заменить .png на .svg. Второе обычно весит меньше и лучшего качества

2023-02-08 20:54 UTC, Kosurij commented
Надо подумать о замене .png на .svg. Второе обычно весит меньше и лучшего качества, да и легче редактируется.

Ну и надо бы избавиться от рамки по контору изображения. Возможно вставить как background-image. Хотя, если вставишь .svg, то проблема уйдет с 99% вероятностью)

2023-02-08 20:56 UTC, Kosurij requested changes

2023-02-08 20:56 UTC, Kosurij commented on packages/client/src/pages/500/500.tsx
>  const Page500 = () => {
Я бы лучше назвал этот как ErrorPage, это более понятное название)

2023-02-09 06:22 UTC, MikhailSamigullin commented on packages/client/src/pages/500/500.tsx
>  const Page500 = () => {
ок!

2023-02-09 06:26 UTC, MikhailSamigullin commented
> Надо подумать о замене .png на .svg. Второе обычно весит меньше и лучшего качества, да и легче редактируется.
png заменю на svg

>Ну и надо бы избавиться от рамки по контору изображения. Возможно вставить как background-image. Хотя, если >вставишь .svg, то проблема уйдет с 99% вероятностью)
скриншоты в ПР не обновил, но еще раз проверю

2023-02-09 11:36 UTC, arudenko-offcl approved these changes
Обсудите с командой подход к путям в импортах плиз.

2023-02-09 11:36 UTC, arudenko-offcl commented on packages/client/src/pages/ErrorPage/ErrorPage.tsx
> +import { breakpoints, paths } from '../../components/App/constants';
Хорошей практикой считается использовать алиасы или хотя бы абсолютный путь от корня проекта. 
Это нужно для того, что бы коллеги легче справлялись с чтением кода

2023-02-09 18:49 UTC, KomAnw requested changes

2023-02-09 18:49 UTC, KomAnw commented on packages/client/src/pages/ErrorPage/ErrorPage.tsx
> +          <br />
Давай сделаем несколько текстовых элементов и отделим их марджинами
```suggestion
          <H3>Что то пошло не так,</H3> // сюда можно накинуть styled (styledH3) и добавить ему margin
          <H3>не переживай</H3>
```

2023-02-09 18:49 UTC, KomAnw commented on packages/client/src/pages/ErrorPage/ErrorPage.tsx
> +const BigText = styled.div`
Возможно в design уже есть такие font правила для шрифта, можно отнаследоваться

2023-02-09 18:49 UTC, KomAnw commented on packages/client/src/pages/ErrorPage/ErrorPage.tsx
> +import { breakpoints, paths } from '../../components/App/constants';
Согласен у нас уже есть алиасы, нужно поюзать их

2023-02-09 19:24 UTC, MikhailSamigullin commented on packages/client/src/pages/ErrorPage/ErrorPage.tsx
> +import { breakpoints, paths } from '../../components/App/constants';
Исправил

2023-02-09 19:32 UTC, MikhailSamigullin commented on packages/client/src/pages/ErrorPage/ErrorPage.tsx
> +          <br />
Сделал

2023-02-09 19:33 UTC, MikhailSamigullin commented on packages/client/src/pages/ErrorPage/ErrorPage.tsx
> +const BigText = styled.div`
+

2023-02-09 19:59 UTC, merged