Feature/225 4 leaderboard
KomAnw/whynot pull request #14
Opened 2023-02-08 12:52 UTC by m0000Amir

### Какую задачу решаем
Страница Leaderboard

### Скриншоты/видяшка (если есть)
![Screenshot 2023-02-08 at 15 44 32](https://user-images.githubusercontent.com/29550018/217533796-83f56af1-fe22-488e-9f1a-e27169913fe3.png)

**Добавил**:
- страницу `LeaderBoard`;
- добавил страницу в `Router`; 
- добавил компонент `LeaderBoardRow` для отрисовки списка;

**Необходимо:**
- добавить наш компонент Link. Сейчас просто заглушка;
- добавить API. Для пятого спринта это не нужно.

На данный момент список берется из папки consts. Когда дадут API, переделаю.

Буду ждать ваших замечаний.

2023-02-08 17:47 UTC, MikhailSamigullin commented on packages/client/src/components/LeaderboardRow/LeaderboardRow.tsx
> +  flex: 1;
Крутая запись! Теперь знаю, что можно так использовать grow, shrink и basis

2023-02-08 17:51 UTC, MikhailSamigullin approved these changes

2023-02-08 20:27 UTC, Kosurij commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +            <div key={rank}>
Можно не оборачивать в див ,а передать key сразу в LeaderboardRow. Чем меньше dom-дерево, тем лучше)

2023-02-08 20:27 UTC, Kosurij commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +const Column = styled.div`
Ты тут используешь `div`, а в LeaderboardRow `li`. Если хочешь сделать семантический список, то нужно заменить `div` на `ul`

2023-02-08 20:27 UTC, Kosurij commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +  font-family: ${({ theme }) => theme.fonts.main};
Мб стоит шрифт установить на уровне `body`, чтобы не определять его тут?

2023-02-08 20:27 UTC, Kosurij commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +  align-items: center;
А для чего тут используешь `flex`? Если для выравнивания по центру, то мб стоит использовать `margin: 0 auto`?

2023-02-08 20:27 UTC, Kosurij commented on packages/client/src/components/LeaderboardRow/LeaderboardRow.tsx
> +const Item = styled(Typography).attrs({ as: 'div' })`
ИМХО, я бы назвал это `RowContent`. Но это больше вкусовщина)

2023-02-08 20:48 UTC, m0000Amir commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +  align-items: center;
А в чем сложность использования здесь `flex`?

2023-02-08 20:50 UTC, m0000Amir commented on packages/client/src/components/LeaderboardRow/LeaderboardRow.tsx
> +const Item = styled(Typography).attrs({ as: 'div' })`
У меня есть уже `Row` в дереве компонента. Я посчитал назвать `Item`, так как внутри находятся все элементы, принадлежащие `Row`.

2023-02-08 23:47 UTC, KomAnw commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +  font-family: ${({ theme }) => theme.fonts.main};
Я все еще верю, что мы дойдем до 2ух шрифтов))

В целом на сколько слышал в body устанавливают веб безопасные шрифты (на случай если основной не загрузится, а уже по компонентам те, которые нужны по дизайну/задумке)
Ничего конкретнее сказать не могу)

2023-02-08 23:50 UTC, KomAnw commented on packages/client/src/components/LeaderboardRow/consts/leaderboardConsts.ts
> +export const leaderboardConsts = [
fyi обычно предпочитают использовать в названии слово mock

2023-02-08 23:56 UTC, KomAnw commented on packages/client/src/design/ListText.tsx
> +export const ListText = styled(Typography).attrs({ as: 'li' })`
Мой фейл

2023-02-09 00:08 UTC, KomAnw requested changes

2023-02-09 00:08 UTC, KomAnw commented on packages/client/src/components/LeaderboardRow/type.ts
> +export type RowProps = {
```suggestion
export type RowProps = Pick<LeaderboardRowProps, 'isMine'>
```

2023-02-09 00:08 UTC, KomAnw commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +  font-weight: 700;
```
export const Label = styled(Typography).attrs({ as: 'li' })
  font-style: normal;
  font-weight: 700;
  font-size: 30px;
  line-height: 34px;
;
```

А зачем мы дублируем стили шрифтов, если они уже прописаны?

2023-02-09 11:41 UTC, arudenko-offcl commented on packages/client/src/components/LeaderboardRow/consts/leaderboardConsts.ts
> +export const leaderboardConsts = [
+за мок в названии, если это тестовые данные или временные для разработки

2023-02-09 11:41 UTC, arudenko-offcl commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +          ))}
Тут можно не деструктуризировать, а просто сделать так например:

```suggestion
          {leaderboardConsts.map((props) => (
            <LeaderboardRow key={props.rank} {...props} />
          ))}
```

2023-02-09 12:43 UTC, MikhailSamigullin commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +          ))}
Хороший способ сократить код! 
Но тут же возникает вопрос читабельности, насколько это удобнее для дальнейшего использования такого кода?

2023-02-09 20:07 UTC, KomAnw commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +          ))}
>Но тут же возникает вопрос читабельности, насколько это удобнее для дальнейшего использования такого кода?

Согласен, когда нужно будет дебажить такого вида компонент, то придется вникать в то, что передается
Но в целом из-за типизации пропсов у нас читабельность сохраняется и все норм

2023-02-10 10:34 UTC, MikhailSamigullin commented on packages/client/src/components/LeaderboardRow/LeaderboardRow.tsx
> +const Row = styled(Label)<RowProps>`
Вот здесь баг:
В консоле выдает:
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.

вкладываешь <div>  в <p>

Можно переопределить вот так:
const Row = styled(Label).attrs({ as: 'div' })<RowProps>

Label наследуется от Typography, а там тэг <p>.
<Item> это <div>

2023-02-10 10:39 UTC, MikhailSamigullin commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +const Link = styled(Label).attrs({ as: 'div' })`
компонент `<Link>` уже готов, можно заменить

2023-02-10 13:26 UTC, KomAnw commented
@m0000Amir 
Нужно подпулить develop и по последним замечаниям доработать

2023-02-11 11:01 UTC, m0000Amir commented
Исправил замечания.

2023-02-11 12:48 UTC, merged