Feature/225 18 page profile
KomAnw/whynot pull request #22
Opened 2023-02-11 14:17 UTC by efes2002

### Какую задачу решаем
Add page Profile
Add page ProfileUpdateData
Add page ProfileUpdatePassword
fixed css-style in Input, Registration, Label

### Скриншоты/видяшка (если есть)
![2023-02-11_16-42-57](https://user-images.githubusercontent.com/65197828/218262822-bc1d33d9-5acb-42c7-8414-8cfada36f44d.png)

![2023-02-11_16-59-40](https://user-images.githubusercontent.com/65197828/218262842-73cd94ae-02f9-4f9d-a813-7e3757d99edf.png)

![2023-02-11_17-03-00](https://user-images.githubusercontent.com/65197828/218262844-0f68daac-3bd5-404c-b23a-c6fcafca9056.png)

### TBD (если есть)

2023-02-11 18:10 UTC, Kosurij requested changes

2023-02-11 18:10 UTC, Kosurij commented on packages/client/src/pages/Profile/Profile.tsx
> +  display: grid;
Тут можно флекс

2023-02-11 18:10 UTC, Kosurij commented on packages/client/src/pages/Profile/Profile.tsx
> +const TextH4 = styled(H3)`
Лучше так не расширять, выше писал почему)

Ну и компонента TextH4, а расширяешь H3

2023-02-11 20:41 UTC, efes2002 commented on packages/client/src/components/Button/Button.tsx
> -    background: ${({ theme, variant }) => theme.colors.control.button[variant].hoverBackground};
Согласен, нужно дождаться все пулреквести и глянуть что бы не кто больше не использует, и если использует то поправить

2023-02-11 20:49 UTC, efes2002 commented on packages/client/src/components/Forms/ProfileData/consts/ProfileDataConsts.ts
> +    placeholder: '',
пока оставил здесь по примеру твой формы, потом удалю когда буду их заполнять из полученных данных

2023-02-11 21:24 UTC, KomAnw requested changes
По сути не так много переделывать, молодец, работа отличная!

2023-02-11 21:24 UTC, KomAnw commented on packages/client/src/components/Button/Button.tsx
> -    background: ${({ theme, variant }) => theme.colors.control.button[variant].hoverBackground};
А почему мы вообще это убираем? Там жеж цвет с опасити стоял rgba

2023-02-11 21:24 UTC, KomAnw commented on packages/client/src/components/Forms/ProfileData/ProfileData.tsx
> +  // eslint-disable-next-line no-console
это пофиг, просто warning не должен мешать тебе пушить

2023-02-11 21:24 UTC, KomAnw commented on packages/client/src/components/Forms/ProfileData/ProfileData.tsx
> +const H1Style = styled(H1)`
```suggestion
const H1Styled = styled(H1)`
 // стили из FormHeader
`
```

2023-02-11 21:24 UTC, KomAnw commented on packages/client/src/components/Forms/ProfileData/ProfileData.tsx
> +const FormHeader = styled(`div`)`
Это лишняя обертка

2023-02-11 21:24 UTC, KomAnw commented on packages/client/src/components/Forms/ProfileData/consts/ProfileDataConsts.ts
> +import {
Зачем нам вообще этот файл, если у нас уже есть все костанты, которые @Kosurij делал, разве они как-то отличаются от этих?

2023-02-11 21:24 UTC, KomAnw commented on packages/client/src/components/Forms/ProfilePassword/ProfilePassword.tsx
> +  // eslint-disable-next-line no-console
По-моему не нужно, дает так запушить

2023-02-11 21:24 UTC, KomAnw commented on packages/client/src/components/Forms/ProfilePassword/ProfilePassword.tsx
> +      <FormHeader>
Это тоже лишняя обертка можно только заголовок оставить и ему стилей накинуть каких надо

2023-02-11 21:24 UTC, KomAnw commented on packages/client/src/components/Forms/ProfilePassword/ProfilePassword.tsx
> +const FormHeader = styled(`div`)`
Нужно будет удалить, а стили переедут в StyledH1 или как там его :)

2023-02-11 21:24 UTC, KomAnw commented on packages/client/src/components/Forms/ProfilePassword/consts/ProfilePasswordConsts.ts
> +import {
Разве такого файла нет? При регистрации мы тоже должны проверять пароли
@Kosurij

2023-02-11 21:24 UTC, KomAnw commented on packages/client/src/design/CenterDivContainer.tsx
> +export const CenterDivContainer = styled(Typography).attrs({ as: 'div' })`
Поддерживаю

А что это вообще, в чем идея? Иметь один общий цетрированный див?

2023-02-11 21:24 UTC, KomAnw commented on packages/client/src/design/MiniDivForm.tsx
> +import styled from 'styled-components';
Тоже не очень понял значение этих компонент

2023-02-11 21:24 UTC, KomAnw commented on packages/client/src/hoc/PrivateRoute/PrivateRoute.tsx
> +  const { isLoading, data = true } = useGetUserQuery();
Видимо забыл убрать?

2023-02-11 21:24 UTC, KomAnw commented on packages/client/src/pages/Profile/Profile.tsx
> +const TextH4 = styled(H3)`
Не так можно, просто есть ли смысл гоняться за семантикой?

2023-02-11 21:24 UTC, KomAnw commented on packages/client/src/pages/Profile/Profile.tsx
> +            <DataValue>Иван</DataValue>
Согласен, хардкод получился

2023-02-11 21:32 UTC, efes2002 commented on packages/client/src/components/Button/Button.tsx
> -    background: ${({ theme, variant }) => theme.colors.control.button[variant].hoverBackground};
При ховере просто добавляем opacity: 0.8; (для нас это и есть замена цвета)

2023-02-11 21:33 UTC, efes2002 commented on packages/client/src/components/Forms/ProfilePassword/ProfilePassword.tsx
> +            key={name}
Ура получилось сделать

2023-02-11 21:52 UTC, efes2002 commented on packages/client/src/components/Forms/ProfileData/ProfileData.tsx
> +const H1Style = styled(H1)`
![2023-02-12_00-51-07](https://user-images.githubusercontent.com/65197828/218282652-448bf19b-1091-43ab-9568-4d3cac6f720e.png)
Без сброшенных margin

В глобальных стилях, margin не сбрасываются у div и даже у P, не знаю почему но их нет там

2023-02-11 22:01 UTC, efes2002 commented on packages/client/src/design/CenterDivContainer.tsx
> +export const CenterDivContainer = styled(Typography).attrs({ as: 'div' })`
Container - Использую для центрирования, в нескольких местах использовал,  вот и вынес отдельно

2023-02-11 22:10 UTC, efes2002 commented on packages/client/src/design/CenterDivContainer.tsx
> +  display: grid;
Grid для меня удобней намного, ему не нужны вот такие костыли, которые плохо читаются ( margin: 27px auto 0;)

2023-02-11 22:28 UTC, efes2002 commented on packages/client/src/design/MiniDivForm.tsx
> +export const MiniDivForm = styled.div`
Это тоже у меня дублируеться вот и вынес, это стил для главного дива таблички, он задает размер, фон, скругления

2023-02-11 22:29 UTC, efes2002 commented on packages/client/src/hoc/PrivateRoute/PrivateRoute.tsx
> +  const { isLoading, data = true } = useGetUserQuery();
Забыл убрать, я так на закрытие роуты захожу

2023-02-11 23:34 UTC, KomAnw commented on packages/client/src/components/Button/Button.tsx
> -    background: ${({ theme, variant }) => theme.colors.control.button[variant].hoverBackground};
@efes2002 посмотри, пожалуйста в цвета, там для всех цветов, где предусмотрен ховер opacity уже прописан в цвете
пример (0.8 - это и есть opacity):
![image](https://user-images.githubusercontent.com/49876296/218285514-b5553465-a0a2-4fa2-8e03-25e29f3ad810.png)

2023-02-11 23:35 UTC, KomAnw commented on packages/client/src/components/Button/Button.tsx
> -    background: ${({ theme, variant }) => theme.colors.control.button[variant].hoverBackground};
Так что надо вернуть обратно цвет...

2023-02-11 23:40 UTC, KomAnw commented on packages/client/src/pages/Profile/Profile.tsx
> +const TextH4 = styled(H3)`
А стоп, тупанул, да, название не совпадает как-то :)
TrxtH4 - может можно заменить на Heading/Title или что-то такое?

2023-02-12 16:23 UTC, Kosurij commented on packages/client/src/components/Forms/ProfileData/ProfileData.tsx
> +const H1Style = styled(H1)`
Пока не пойму почему переопределяются стили, но тогда тут два 2 варианта:

Добавить специфичности, тогда все будет работать как надо 
```
body * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }
```

Либо описать все вручную:
```
 h1, h2, h3, h4, h5, h6, p {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }
```

2023-02-12 16:23 UTC, Kosurij commented on packages/client/src/components/Forms/ProfilePassword/ProfilePassword.tsx
> +  // eslint-disable-next-line no-console
Там стоит варнинг, а не ошибка. Запушишь и без дизейбла правила

2023-02-12 16:23 UTC, Kosurij commented on packages/client/src/components/Forms/ProfilePassword/consts/ProfilePasswordConsts.ts
> +import {
Можно создать общий файл всех полей

2023-02-12 16:23 UTC, Kosurij commented on packages/client/src/design/CenterDivContainer.tsx
> +  display: grid;
Так а почему `display: grid`, а не `display: flex`. В твоем случае они будут вести себя идентично же, не?

2023-02-13 07:10 UTC, MikhailSamigullin commented on packages/client/src/components/Button/Button.tsx
> -    background: ${({ theme, variant }) => theme.colors.control.button[variant].hoverBackground};
давайте цвет оставим. 
Если используем прозрачность, например, 0.8, то получается, что итоговый цвет будет состоять на 80% из цвета верхнего слоя и на 20% из цвета фона. В итоге это может отличаться от дизайна))

2023-02-13 07:13 UTC, MikhailSamigullin commented on packages/client/src/components/Button/Button.tsx
> -    background: ${({ theme, variant }) => theme.colors.control.button[variant].hoverBackground};
![Screenshot from 2023-02-13 11-12-27](https://user-images.githubusercontent.com/109307026/218393753-600ef329-1c25-4074-9408-7e355a8faa84.png)
![Screenshot from 2023-02-13 11-11-30](https://user-images.githubusercontent.com/109307026/218393762-711c173e-706a-4e81-a7c9-89435eb29211.png)

при наведении получается оранжевый  цвет, а должен быть бледнокрасный

2023-02-13 07:36 UTC, Kosurij commented on packages/client/src/components/Forms/ProfileForm/ProfileForm.tsx
> +          Редактировать данные
Тут должен быть инглиш)

2023-02-13 07:36 UTC, Kosurij commented on packages/client/src/pages/Profile/type.ts
> +  avatar?: string;
Давай будем сохранять порядок свойств: сперва обязательные, потом опциональные? Так визуально проще сразу увидеть обязательные свойства и не искать их глазами по всему объекту)

2023-02-13 20:44 UTC, efes2002 commented on packages/client/src/components/Button/Button.tsx
> -    background: ${({ theme, variant }) => theme.colors.control.button[variant].hoverBackground};
Хороший пример привел, я его возьму на заметку, в нашем случае opacity нечего не поломает, не логику, не цвет, у нас фоны и кнопки одинаковые, и везде будет один и тот же эффект. Молодец что мне объяснил его коварность.

2023-02-14 16:03 UTC, KomAnw commented
Ждем оставшиеся правки

2023-02-14 16:03 UTC, KomAnw commented
@efes2002 
Ждем оставшиеся правки + нужно зарезолвить конфликты

2023-02-14 17:15 UTC, arudenko-offcl requested changes
Ребята, очень круто, что активно и продуктивно разобрались все вместе. Действительно нужно порезолвить конфликты, после этого дополнительно позовите меня в ПР плиз

2023-02-14 23:38 UTC, KomAnw approved these changes
Для меня окей

@m0000Amir, @Kosurij, @MikhailSamigullin, @arudenko-offcl

2023-02-15 07:53 UTC, Kosurij approved these changes

2023-02-15 07:53 UTC, Kosurij commented on packages/client/src/components/Forms/ProfileData/ProfileData.tsx
> +  const submitForm = (data: any) => console.log(data);
Вот тут нужно заменить на тип отправляемых данных

2023-02-15 07:53 UTC, Kosurij commented on packages/client/src/components/Forms/ProfilePassword/ProfilePassword.tsx
> +                  return 'Your passwords do no match';
Букву t потерял - Your passwords do no**t** match

2023-02-15 07:53 UTC, Kosurij commented on packages/client/src/components/Forms/consts/types.ts
> +interface TypeValidate {
Договорились не использовать интерфейсы

2023-02-15 14:48 UTC, KomAnw commented on packages/client/src/components/Forms/ProfileData/ProfileData.tsx
> +  const submitForm = (data: any) => console.log(data);
Договорились что эта задачка для того, кто апи подключает

2023-02-16 07:45 UTC, merged