Feature/225 85 profile api
KomAnw/whynot pull request #30
Opened 2023-02-14 08:30 UTC by MikhailSamigullin

### Добавление API  для страниц профиля

API необходим для изменения данных, аватара и пароля пользователя

2023-02-14 08:32 UTC, MikhailSamigullin commented
Если я все правильно понял, то для тестирования API нужны страницы редактирования? Или можно как то дебажить с моковыми данными?

2023-02-14 09:29 UTC, efes2002 commented on packages/client/src/api/user/models.ts
> +  password: string;
По Api нам не нужно оправлять пароль в данных пользователя.

2023-02-14 09:29 UTC, efes2002 commented on packages/client/src/api/user/models.ts
> +};
Ты забыл добавить "display_name"

2023-02-14 09:31 UTC, efes2002 commented on packages/client/src/api/user/models.ts
> +  password: string;
Здесь тоже самое, пароль нам в этих данных не нужен (его нет в этой ручке Api).

2023-02-14 09:38 UTC, efes2002 commented on packages/client/src/api/user/user.ts
> +      query: passwordData => ({ url: USER_ENDPOINTS.password, method: 'PUT', body: passwordData }),
Здесь в ответ мы получаем строку со значением 'OK', а в данных отправляем вот такой json:
{ "login": "string",  "password": "string"}, 
нужно описать тогда новый TChangePassword и получиться вот что такое: 
changePassword: build.mutation<string, TChangePassword >

2023-02-14 17:33 UTC, arudenko-offcl requested changes

2023-02-15 08:02 UTC, Kosurij requested changes

2023-02-16 08:39 UTC, MikhailSamigullin commented on packages/client/src/api/user/models.ts
> +};
готово

2023-02-16 08:40 UTC, MikhailSamigullin commented on packages/client/src/api/user/user.ts
> +      query: passwordData => ({ url: USER_ENDPOINTS.password, method: 'PUT', body: passwordData }),
подправил исходя из получаемых и отправляемых данных в Свагере

2023-02-16 08:43 UTC, MikhailSamigullin commented on packages/client/src/api/user/user.ts
> +    changeAvatar: build.mutation<TUserData, FormData>({
подойдет ли такой тип, как FormData? Вроде ее отправляем

2023-02-16 14:45 UTC, arudenko-offcl requested changes
Поправить бы FormData и будет 🔥

2023-02-16 14:45 UTC, arudenko-offcl commented on packages/client/src/api/user/models.ts
> +};
Гуд, но как будто бы пока можно сделать даже так
```suggestion
export type TUserData = Omit<TUser, 'password'> & { display_name: string };
```

2023-02-16 14:45 UTC, arudenko-offcl commented on packages/client/src/api/user/user.ts
> +    changeAvatar: build.mutation<TUserData, FormData>({
Ноуп, это означает, что ты можешь в эту ручку любую форму отправить и это будет валидный запрос. ЛУчше описать нужные поля

2023-02-17 15:27 UTC, arudenko-offcl approved these changes

2023-02-17 22:42 UTC, KomAnw commented
не мержете пожалуйста, хочу посмотреть завтра днем

2023-02-18 01:12 UTC, merged