[WIP] 225-83-game
KomAnw/whynot pull request #31
Opened 2023-02-14 09:04 UTC by Kosurij

Добавлена возможность отрисовки платформ, игрока и его горизонтальные движения.

2023-02-15 08:52 UTC, Kosurij commented on packages/client/src/pages/Game/Game.tsx
> +      player.xPosition += player.currentXPosition;
Пробовал, потеряем в плавности анимации и скорости

2023-02-16 14:32 UTC, arudenko-offcl requested changes
Анимированная демка – круто! 🔥 

Есть вопросы про тайпкасты в компоненте и статические поля в классе Platforms.

2023-02-16 14:32 UTC, arudenko-offcl commented on packages/client/src/pages/Game/Game.tsx
> +    canvasContextRef.current = canvas.getContext('2d');
Я думаю, таких самонадеянных тайпкастов лучше избегать. 
Ты здесь перезаписываешь потенциальный null, как я понимаю. 
Лучше строчкой ниже проверяй, что у тебя нет null, например так:
```suggestion
    const canvas = canvasRef.current;

    canvasContextRef.current = canvas ? canvas.getContext('2d') : null;
```

2023-02-16 14:32 UTC, arudenko-offcl commented on packages/client/src/pages/Game/Game.tsx
> +  let ground = new Ground(canvasContextRef.current as CanvasRenderingContext2D, sizes);
Два раза в файле кладешь сюда инстансы, а тут еще и с тайпкастом. 

Выглядит подозрительно ) 

Можно создать просто пустые переменные с типизацией, а там, где необходимо (в функции init), уже положить экземпляры. Так будет логичнее и мы не будем обманывать атйпскрипт )

2023-02-16 14:32 UTC, arudenko-offcl commented on packages/client/src/pages/Game/Game.tsx
> +    document.addEventListener('keydown', e => {
Как насчет того,  чтобы предусмотреть отписку от этих событий при анмаунте компонента с игрой? 
Отписка от событий хорошая практика!

2023-02-16 14:32 UTC, arudenko-offcl commented on packages/client/src/pages/Game/controllers/Platforms/Platforms.ts
> +  static platforms: Platform[] = [];
Не совсем понимаю – почему почему эти свойства статические?

2023-02-16 14:32 UTC, arudenko-offcl commented on packages/client/src/pages/Game/controllers/Platforms/Platforms.ts
> +  static platforms: Platform[] = [];
Вероятно, чтобы передавать данные из этого класса в другие. тогда нужно немного по-другому спроектировать. 

НАпример, передавать экземпляр Platforms в экземпляр Player'a

2023-02-16 15:06 UTC, Kosurij commented on packages/client/src/pages/Game/controllers/Platforms/Platforms.ts
> +  static platforms: Platform[] = [];
Это был первоначальный вариант, но тогда нужно добавлять дополнительный аргумент в инстанс класса Player, а из всего класса мне будет нужно всего одно свойство)

Разве в таком случае не лучше использовать статическое свойство?

2023-02-16 15:08 UTC, Kosurij commented on packages/client/src/pages/Game/Game.tsx
> +  let ground = new Ground(canvasContextRef.current as CanvasRenderingContext2D, sizes);
Хорошее предложение, согласен)

2023-02-16 18:28 UTC, Kosurij commented on packages/client/src/pages/Game/Game.tsx
> +    canvasContextRef.current = canvas.getContext('2d');
Исправил

2023-02-16 18:29 UTC, Kosurij commented on packages/client/src/pages/Game/Game.tsx
> +    document.addEventListener('keydown', e => {
Добавил при размонтировании компонента

2023-02-16 20:07 UTC, Kosurij commented on packages/client/src/pages/Game/controllers/Platforms/Platforms.ts
> +  static platforms: Platform[] = [];
В итоге отказался от абстрактных свойств

2023-02-17 10:38 UTC, Kosurij commented
> 

@arudenko-offcl Внес изменения, глянь плиз

2023-02-17 15:39 UTC, arudenko-offcl commented on packages/client/src/pages/Game/controllers/Platforms/Platforms.ts
> +  static platforms: Platform[] = [];
> Разве в таком случае не лучше использовать статическое свойство?

Я лично не вижу ничего страшного в этом )

2023-02-17 15:40 UTC, arudenko-offcl approved these changes
Кайф! 🔥

2023-02-17 15:40 UTC, arudenko-offcl commented on packages/client/src/pages/Game/controllers/Platforms/Platforms.ts
> +  data: Platform[] = [];
Я бы правда что-то вроде platformList назвал, ну это опционально

2023-02-17 20:45 UTC, merged