Feature/225 77 popup edit avatar
KomAnw/whynot pull request #38
Opened 2023-02-20 19:56 UTC by efes2002

### Какую задачу решаем
Добавлен Popup для изменения Аватара пользователя
Подключено Api для отправки запроса на изменение.

### Скриншоты/видяшка (если есть)
![2023-02-20_22-54-04](https://user-images.githubusercontent.com/65197828/220188972-fed293f9-4fe4-4bac-bdd3-7b5444c3e176.png)

### TBD (если есть)

2023-02-21 07:00 UTC, MikhailSamigullin approved these changes

2023-02-21 07:00 UTC, MikhailSamigullin commented on packages/client/src/components/Forms/ProfileForm/ProfileForm.tsx
> +      <Avatar src={defaultAvatar} onClick={openPopup} />
можешь уже выводить аватар
вместо defaultAvatar подставь:
https://ya-praktikum.tech/api/v2/resources/ + путь до файла, который получаешь

2023-02-21 16:31 UTC, arudenko-offcl requested changes
С чем связано понижение мажорной версии react-redux? 
Довольно серьезный даунгрейд, хочется понимать, зачем он и насколько необходим.

Кроме того, откуда package-lock..json в репозитории? КАжется, все пользуются yarn в команде

2023-02-22 07:45 UTC, KomAnw requested changes

2023-02-22 07:45 UTC, KomAnw commented on packages/client/src/pages/Profile/pages/ProfileUpdateAvatar/ProfileUpdateAvatar.tsx
> +
от файла к файлу отличается форматирование, где-то есть пробелы между хуками, где-то нет...
Давай приведем к общему виду?

2023-02-22 07:45 UTC, KomAnw commented on packages/client/src/pages/Profile/pages/ProfileUpdateAvatar/ProfileUpdateAvatar.tsx
> +  const submitForm: SubmitHandler<FieldValues> = async data => {
Нужно типизировать, FieldValues не подходит в качестве типа, у тебя data с типом any

2023-02-22 07:45 UTC, KomAnw commented on packages/client/src/pages/Profile/pages/ProfileUpdateAvatar/types.ts
> +  register: UseFormRegister<FieldValues>;
когда типизируешь будет ругаться что FieldValues и твой тип не совместимы, тут надо просто any поставить вместо FieldValues, решения этому нет

2023-02-22 07:47 UTC, KomAnw commented
@arudenko-offcl 
>С чем связано понижение мажорной версии react-redux?
>Довольно серьезный даунгрейд, хочется понимать, зачем он и насколько необходим.

Мы наткнулись что в некоторых случаях внутренние зависимости ломаются и redux валит все приложение, нашли треды с этой ошибкой, решения у команды redux еще нет

2023-02-22 09:49 UTC, Kosurij commented
> 

У некоторых ребят из команды возникла такая ошибка - https://stackoverflow.com/questions/73508005/rtk-query-error-could-not-find-react-redux-context-value-please-ensure-the-com

Вот issue на гитхабе, которая возникает как раз на 8 версии - https://github.com/reduxjs/redux-toolkit/issues/2715

Как ее решить - хз, т.к. она воспроизводилась у 2х человек из 5. Помогло понижение мажорной версии до предыдущей

2023-02-22 09:53 UTC, Kosurij commented
Нужно удалить package-lock.json, т.к. целевой пакетный менеджер у нас yarn

2023-02-22 10:01 UTC, Kosurij requested changes

2023-02-22 10:01 UTC, Kosurij commented on packages/client/src/pages/Profile/pages/ProfileUpdateAvatar/ProfileUpdateAvatar.tsx
> +  text-overflow: ellipsis;
Лишнее свойство, т.к. ты руками ставишь `...`

2023-02-22 10:01 UTC, Kosurij commented on packages/client/src/pages/Profile/pages/ProfileUpdateAvatar/ProfileUpdateAvatar.tsx
> +  overflow: hidden;
Это тоже лишнее

2023-02-22 10:01 UTC, Kosurij commented on packages/client/src/pages/Profile/types.ts
> +  setIsOpenPopup: Dispatch<boolean>;
А зачем тут dispatch? 

Можно просто: (value: boolean) => void

2023-02-22 17:47 UTC, efes2002 commented on packages/client/src/components/Forms/ProfileForm/ProfileForm.tsx
> +      <Avatar src={defaultAvatar} onClick={openPopup} />
Данный функционал я добавил в ПР225-105 Подгрузка данных профиля

2023-02-22 17:56 UTC, efes2002 commented on packages/client/src/pages/Profile/Profile.tsx
>  const valueData: TypeDataProfile = {
будет изменено  в ПР-225-105

2023-02-22 18:07 UTC, efes2002 commented on packages/client/src/pages/Profile/pages/ProfileUpdateAvatar/ProfileUpdateAvatar.tsx
> +  font-family: Arial, serif;
'х', в нашем шрифте, ну очень уж отвратный и на символ закрытия не тянет не как

2023-02-22 19:43 UTC, efes2002 commented on packages/client/src/pages/Profile/pages/ProfileUpdateAvatar/ProfileUpdateAvatar.tsx
> +  position: absolute;
с твоим вариантом у меня не получилось, там нюанс есть, что этот стиль еще отвечает за расскатывае черного фона на всю область экрана и одновременно он еще центрирует дочерний элемент.

2023-02-22 19:57 UTC, efes2002 commented on packages/client/src/pages/Profile/pages/ProfileUpdateAvatar/ProfileUpdateAvatar.tsx
> +  text-overflow: ellipsis;
хотел красиво сделать обрезание длинного имени файла который не помещается в область, но к сожалению оно не заработало.

2023-02-22 20:01 UTC, efes2002 commented on packages/client/src/pages/Profile/pages/ProfileUpdateAvatar/ProfileUpdateAvatar.tsx
> +  overflow: hidden;
это не лишнее, что бы увидеть разницу, нужно прикрепить файл с начало с коротким именем потом с длинным, маленькое имя будет красиво отцентрировано по центру, большое будет начинаться ровно с начала.

2023-02-23 14:38 UTC, arudenko-offcl approved these changes
Обрати внимание на комменты коллег)

По поводу версии редакса понял, попробую посмотреть, что можно сделать и как полечить!

2023-02-23 15:36 UTC, arudenko-offcl commented on yarn.lock
> +  resolved "https://registry.npmjs.org/@ampproject/remapping/-/remapping-2.2.0.tgz"
Из-за того, что ты заюзал npm, пакеты в ярне "нацелились" на npm-реджистри.
Нужно откатить yarn.lock до состояния исходной ветки и заново установить все ярном)
```
git checkout develop yarn.lock
yarn bootstrap
```

2023-02-23 17:05 UTC, Kosurij commented on packages/client/src/pages/Profile/pages/ProfileUpdateAvatar/ProfileUpdateAvatar.tsx
> +  font-family: Arial, serif;
> 'х', в нашем шрифте, ну очень уж отвратный и на символ закрытия не тянет не как

Мб тогда вставит иконку?

2023-02-25 05:24 UTC, merged