Feature/225 56 input component
KomAnw/whynot pull request #4
Opened 2023-02-04 16:10 UTC by m0000Amir

### Добавил компонент Input.

Буду рад вашим замечаниям.
Особенно по styled components и передаваемым props'ам.

2023-02-04 16:36 UTC, KomAnw commented on packages/client/src/components/Input/Input.tsx
> +export const Input: FC<InputProps> = (props) => {
1.  Давай сразу деструкторизацию пропов сделаем?

2. Довольно холиварная тема, но чаще склоняются к тому, чтобы типизировать пропы, вместо компонента, давай поменяем?

2023-02-04 19:33 UTC, Kosurij requested changes

2023-02-04 19:33 UTC, Kosurij commented on packages/client/src/components/Input/Input.tsx
> +  type: string;
Эти свойства есть в `InputHTMLAttributes<HTMLInputElement>`, можно не описывать здесь)

А вообще стоит подумать нужно ли нам такая кастомизация инпута. Возможно стоит свести ее к минимуму, ведь мы описываем элемент ui kit'а. То, о чем говорили с Мишей по поводу кнопки на созвоне. Тогда будет достаточно базовых вещей: value, onChange, placeholder и т.д.  и не нужно будет расширяться с помощью InputHTMLAttributes<HTMLInputElement>

2023-02-04 19:33 UTC, Kosurij commented on packages/client/src/components/Input/Input.tsx
> +  return (
Нужно сделать компонент управляемым.

https://ru.reactjs.org/docs/forms.html#controlled-components

2023-02-05 11:14 UTC, MikhailSamigullin approved these changes

2023-02-05 17:41 UTC, m0000Amir commented
## Скриншот компонента
![Screenshot 2023-02-05 at 20 18 00](https://user-images.githubusercontent.com/29550018/216835362-091348bd-
fe0a-4a3d-8327-48d50dc48c4a.png)

### Сделано:
- добавил label к компоненту Input;
-  добавил хук для отрисовки label (в случае ввода значений в input, вместо placeholder появляется label;
- заменил interface на type;
- использую утилиту Pick для описание пропсов.

### Что надо сделать:
- необходимо добавить RegEx для вводимых параметров;
- определить как будет проходить валидация: через пропсы или непосредственно в компоненте проводить проверку.

Буду ждать ваших замечаний!

2023-02-05 17:43 UTC, m0000Amir commented on packages/client/src/components/Input/Input.tsx
> +export const Input: FC<InputProps> = (props) => {
Заменил interface на type

2023-02-05 17:44 UTC, m0000Amir commented on packages/client/src/components/Input/Input.tsx
> +  type: string;
Убрал `InputHTMLAttributes<HTMLInputElement>`

2023-02-05 17:44 UTC, m0000Amir commented on packages/client/src/components/Input/Input.tsx
> +  return (
добавил хуки.

2023-02-05 20:55 UTC, arudenko-offcl requested changes
👌  но есть вопросики, на которые хочется понять ответы )

2023-02-05 20:55 UTC, arudenko-offcl commented on packages/client/src/components/Input/Input.tsx
> +  type: string;
Согласен с @Kosurij, если весь ётот перечень пропсов не описан изначально в задаче, то лучше добавлять их итеративно, по мере необходимости.

2023-02-05 20:55 UTC, arudenko-offcl commented on packages/client/src/components/Input/Input.tsx
> +        value={props.value}
Выше ты уже спредишь пропсы
Для чего здесь ты их снова дополнительно передаешь?

2023-02-05 20:55 UTC, arudenko-offcl commented on packages/client/src/components/Input/Input.tsx
> +  const [state, setState] = useState('');
Из названия стейта должно быть понятно, что это за состояние) Здесь я вижу, что ты сеттишь сюда вводимое значение. 

Может быть [value, setValue] ?

2023-02-05 20:55 UTC, arudenko-offcl commented on packages/client/src/components/Input/Input.tsx
> +  const handler = (e: React.ChangeEvent<HTMLInputElement>) => {
А вообще, давай поймем, для чего нужен этот хендлер? Он передается инпуту только если не передан пользовательский обработчик?

2023-02-05 21:00 UTC, arudenko-offcl commented
Про валидацию: постарайтесь делать компоненты максимально "глупыми" – например,  пусть они просто принимают извне проп для валидации значения. 
Про пропсы: не торопитесь! Лучше итеративно добавлять пропсы, чем тратить лишнее время сейчас на продумывание будущего, которое может и не случиться) Итеративная разработка же )

2023-02-05 21:14 UTC, KomAnw requested changes

2023-02-05 21:14 UTC, KomAnw commented on packages/client/src/components/Input/Input.tsx
> +type InputProps = {
Давай сделаем так:

```suggestion
type InputProps = {
  type: string;
  placeholder: string;
  value?: string;
  onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;
  validationText?: string;
};

const Input = (props: InputProps) => {
```

И перенесем эти типы в отдельный файл types.ts

2023-02-05 21:14 UTC, KomAnw commented on packages/client/src/components/Input/Input.tsx
> +type InputProps = {
Все что касается цвета и т.д. мы будем брать из темы, не прокидывая напрямую

2023-02-05 21:14 UTC, KomAnw commented on packages/client/src/components/Input/Input.tsx
> +  color: ${props => props.validationTextColor || 'red'};
все цвета мы будем брать примерно так, пока еще четкой структуры нет, как и самих цветов, так что пускай пока отрабатывают фолбэки 'red' и другие запасные цвета
```suggestion
  color: ${({ theme }) => theme.input.validationTextColor || 'red'};
```

2023-02-05 21:14 UTC, KomAnw commented on packages/client/src/components/Input/Input.tsx
> +const Input = (props: InputProps) => {
Давай деструкторизируем пропы

2023-02-05 21:14 UTC, KomAnw commented on packages/client/src/components/Input/Input.tsx
> +        {...props}
Этого пока нам будет не нужно, но если понадобится кастомить компонент - прикрутим обратно, заранее не будем продумывать все детали

2023-02-05 21:14 UTC, KomAnw commented on packages/client/src/components/Input/Input.tsx
> +  width: ${props => props.width || '350px'};
Давай просто поумолчанию пока сделаем так:
```suggestion
  width: 100%;
```
Она будет зависеть от ширины контейнера, если все же нам понадобится кастомить ширину прикрутим обратно (пока что как будто бы нам это не нужно)

2023-02-05 21:26 UTC, KomAnw commented on packages/client/src/components/Input/Input.tsx
> +  const handler = (e: React.ChangeEvent<HTMLInputElement>) => {
Просто контрлируемый инпут, потому что когда он резко превращается из неконтролируемого в контролируемый - реакт начинает орать, а такой кейс будет у нас с паролями

2023-02-06 14:19 UTC, m0000Amir commented
- убрал все стили из пропсов;
- завел `types.ts`.

2023-02-06 14:19 UTC, m0000Amir commented on packages/client/src/components/Input/Input.tsx
> +  width: ${props => props.width || '350px'};
Исправил

2023-02-06 14:19 UTC, m0000Amir commented on packages/client/src/components/Input/Input.tsx
> +        {...props}
Убрал useEffect.

2023-02-06 14:20 UTC, m0000Amir commented on packages/client/src/components/Input/Input.tsx
> +const Input = (props: InputProps) => {
Так как больше не передаю пропсы стилей, убрал типы для styled.

2023-02-06 14:20 UTC, m0000Amir commented on packages/client/src/components/Input/Input.tsx
> +  color: ${props => props.validationTextColor || 'red'};
Убрал, когда будут темы, добавлю.

2023-02-06 14:21 UTC, m0000Amir commented on packages/client/src/components/Input/Input.tsx
> +type InputProps = {
Сделано!

2023-02-06 14:21 UTC, m0000Amir commented on packages/client/package.json
> +    "eslint-config-airbnb-base": "15.0.0",
Исправил!

2023-02-06 14:21 UTC, m0000Amir commented on packages/client/src/components/Input/Input.tsx
> +  const [state, setState] = useState('');
Исправил.

2023-02-06 14:21 UTC, m0000Amir commented on packages/client/src/components/Input/Input.tsx
> +        value={props.value}
Моя ошибка, не заметил при коммите.

2023-02-07 01:42 UTC, KomAnw requested changes
Почти все, осталось чуть-чуть)

2023-02-07 01:42 UTC, KomAnw commented on packages/client/src/components/Input/type.ts
> +  isValid?: boolean;
Это не нужно будет

2023-02-07 01:42 UTC, KomAnw commented on packages/client/src/components/Input/Input.tsx
> +      <ValidationStyled>{props.isValid ? '' : props.validationText}</ValidationStyled>
Лучше, как мне кажется, если название будет ErrorMessage
И мы можем сделать условный рендеринг, если проп есть - показывать компоненту, если нет, то ничего не показывать, тогда таким образом мы можем избавиться от isValid

2023-02-07 01:42 UTC, KomAnw commented on packages/client/src/components/Input/Input.tsx
> +const DivStyled = styled.div`
Давай назовем DivStyled => Container/InputContainer

Стяни пожалуйста develop, там обновился theme, который доступен в любом styled-component, нужно заполнить цвета по его структуре без fallback"ов, также там доступен шрифт, однако размеры толщина и т.д. все еще отвественность этого компонента

2023-02-07 05:38 UTC, MikhailSamigullin commented on packages/client/src/components/Input/Input.tsx
> +const DivStyled = styled.div`
Нужно что то вот такого типа:
color: ${({ theme, variant }) => theme[variant].button.color }; // ссылку нужно указывать уже на реальную тему в файле ../../components/App/constants, там будет theme. 
Внутри:
` default: {
    name: 'default',
    colors: {
      core: {
        background: {
          primary: 'white',
          secondary: 'blue',
        },
        text: {
          primary: 'black',
          secondary: 'green',
          error: 'red',
        },
        link: {
          link: 'blue',
          linkHover: '#03a9f4',
        },
      },
      control: {
        input: {
          primary: 'black',
          secondary: 'green',
        },
...
...`
Редактируешь то, что относится к инпуту. Например, если есть будут атрибуты типа primary или secondary:
`input: {
          primary: {
color: 'white',
background: 'black'
},
          secondary:{
color: 'black',
background: 'white'
},
        },`

Или можешь просто:
`input: {
  color: 'white',
  background: 'black',
.... ,
...
        },`

Главный момент: 
Если добавляешь данные в одну тему, то необходимо добавить их и в другую. А еще в файле packages/client/src/hoc/ThemeWrapper/types.ts необходимо добавлять типы для данных, которые ты добавил))

Можешь постотреть еще мою ветку [Feature/225 56 input component]
(https://github.com/KomAnw/whynot/pull/4/files#top)
там, конечно, нужно стилизацию сделать и подключиться к стилям, но общая идея есть)))

2023-02-07 15:24 UTC, m0000Amir commented
Добавил theme.

2023-02-07 20:06 UTC, arudenko-offcl requested changes
Монументальная работа с ПРом проделана )
Еще пара штрихов!

2023-02-07 20:06 UTC, arudenko-offcl commented on packages/client/src/components/Input/Input.tsx
> +  const handler = (e: React.ChangeEvent<HTMLInputElement>) => {
Я предлагаю называть методы глаголами по возможности, например handleClick, чтобы было чуть понятнее. Это правда удобно )

Ну и ниже, условно передавая этот хендлер инпуту, ты немного ломаешь контрлируемость, тк в некоторых случаях состояние будет меняться, а в некоторых (когда передан onChange) не будет. 

Предлагаю передавать хендлер, изменяющший состояние всегда и внутри него вызывать пользовательский onChange, если он передан )

2023-02-07 20:06 UTC, arudenko-offcl commented on packages/client/src/components/Input/Input.tsx
> +        value={value || iternalValue}
Кажется, надо задать value как initial state для твоего iternalValue а здесь всегда передавать iternalValue

2023-02-07 20:06 UTC, arudenko-offcl commented on packages/client/src/components/Input/Input.tsx
> +        value={value || iternalValue}
и нет ли опечатки? Не internalValue должно быть ? )

2023-02-07 21:00 UTC, KomAnw commented on packages/client/src/components/Input/Input.tsx
> +        value={value || iternalValue}
Кстати да, валидно)

2023-02-08 08:39 UTC, MikhailSamigullin approved these changes

2023-02-08 22:25 UTC, KomAnw commented
Выглядит окей теперь, еще чуть позже обдумаем, на счет валидации, возможно onchange & value будут не нужны

2023-02-08 22:26 UTC, merged