Added password changes
KomAnw/whynot pull request #40
Opened 2023-02-21 21:33 UTC by efes2002

### Какую задачу решаем
Добавлено новое поле для старого пароля, и подключено Api изменения пароля.

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-02-22 07:57 UTC, KomAnw requested changes

2023-02-22 07:57 UTC, KomAnw commented on packages/client/src/components/Forms/ProfilePassword/ProfilePassword.tsx
> +  const submitForm: SubmitHandler<FieldValues> = async data => {
data - any, нужно типизировать ожидаемые поля

2023-02-22 07:57 UTC, KomAnw commented on packages/client/src/components/Forms/ProfilePassword/ProfilePassword.tsx
> +          errorMessage={errors[oldPassword.name]?.message as string}
Если мы делаем "as string" - значит в 95% случаях что-то не так с типизацией
Надо начать с типизации onSubmit'a, затипизировать поля формы и сам хук
Можно нагуглить доку как это делается и тогда типы не придется прописывать насильно

2023-02-22 07:57 UTC, KomAnw commented on packages/client/src/components/Forms/ProfilePassword/ProfilePassword.tsx
> +        <Input
Можем ли мы тут через map все сделать?

2023-02-23 16:49 UTC, arudenko-offcl commented on packages/client/src/components/Forms/ProfilePassword/ProfilePassword.tsx
> +          errorMessage={errors[oldPassword.name]?.message as string}
Да, тут попытка сузить тип, лучше этого избегать!

Есть вероятность, что тут может быть не строка в `.message`

2023-02-24 02:42 UTC, merged