Feature/225 98 sprite
KomAnw/whynot pull request #43
Opened 2023-02-22 11:13 UTC by m0000Amir

### Добавил default sprite

### Скриншоты/видяшка (если есть)
![Screenshot 2023-02-22 at 14 11 23](https://user-images.githubusercontent.com/29550018/220603819-64813070-3212-4bba-b5b7-22a2aafb5c66.png)

2023-02-22 13:49 UTC, Kosurij requested changes

2023-02-22 13:49 UTC, Kosurij commented on packages/client/src/pages/Game/Game.tsx
> +      player.isLooking2left = player.isMovingLeft;
Обычно отказываются от цифр в нейминге, т.к. явно лучше неявного)

Можно назвать` isLookingToleft` или `isLeftDirection`. Ну или в этом духе что-то

2023-02-22 13:49 UTC, Kosurij commented on packages/client/src/pages/Game/Game.tsx
> +    const sprite = new Image() as HTMLImageElement;
А если не кастить, а сделать так  ` const sprite: HTMLImageElement = new Image() `?

2023-02-22 13:49 UTC, Kosurij commented on packages/client/src/pages/Game/controllers/Ground/Ground.ts
> +  cx = 0;
Может назовем более явно?  Например `spriteXPosition`

ну и далее ниже

2023-02-22 13:49 UTC, Kosurij commented on packages/client/src/pages/Game/controllers/Platforms/Platforms.ts
> +// export default withTheme(Platforms);
Тут комментарий забыл убрать

2023-02-22 16:45 UTC, MikhailSamigullin approved these changes

2023-02-23 06:54 UTC, Kosurij approved these changes

2023-02-23 17:07 UTC, arudenko-offcl commented on packages/client/src/pages/Game/Game.tsx
> +    const sprite: HTMLImageElement = new Image();
Тип необязательно указывать, тс достаточно умный, чтобы взять его из экземпляра класса Image()

2023-02-23 17:07 UTC, arudenko-offcl commented on packages/client/src/pages/Game/modeSlice.ts
> +export default modeSlice.reducer;
На мой взгляд, несколько странное расположение слайса 🤔 

Не было бы удобнее расположить их в одном месте, например возле стора?

2023-02-25 05:22 UTC, KomAnw approved these changes
После исправлений можно мержить, и нужно подлить develop, возможно будут конфликты из-за меня (сори, если что пиши порешаем вместе)

На счет стора, я лично так и не понял, мне в целом нравится хранить все вместе, однако яндекс говорит, что хранить все можно и раздельно, там, где этот стор нужен, давай тогда и мой слайс перенесем поближе к стору, если ты выберешь такой вариант?

2023-02-26 10:11 UTC, arudenko-offcl approved these changes
Относительно места расположения слайсов – не крит, на усмотрение вас, как команды!

2023-02-27 21:54 UTC, merged