Feature/225 99 sprite changing
KomAnw/whynot pull request #44
Opened 2023-02-22 17:29 UTC by m0000Amir

### Добавил смену `mode` в `Settings`.

### Скриншоты/видяшка (если есть)
<img width="847" alt="Screenshot 2023-02-22 at 20 26 10" src="https://user-images.githubusercontent.com/29550018/220707990-22b8dac5-9472-4bb3-b56f-0d899bd2d420.png">

2023-02-23 17:09 UTC, arudenko-offcl approved these changes
Если ты берешь код из ветки, по которой уже создан ПР, то новый ПР лучше открывать в исходную ветку) 

Тогда будет совсем небольшой дифф в ПР, который будет легко ревьювить коллегам!)

2023-02-24 08:44 UTC, Kosurij requested changes

2023-02-24 08:44 UTC, Kosurij commented on packages/client/src/pages/Settings/Settings.tsx
> +  const dispatch = useDispatch();
Используй тут `useAppDispatch`, он сразу накидывает типизацию

2023-02-24 08:44 UTC, Kosurij commented on packages/client/src/pages/Settings/Settings.tsx
> +  const sprite = useSelector((state: RootState) => state.mode.sprite);
А тут `useAppSelector`, по той же причине)

2023-02-24 08:44 UTC, Kosurij commented on packages/client/src/pages/Game/Game.tsx
> +  const mode = useSelector((state: RootState) => state.mode.sprite);
используй useAppSelector, там уже есть типизация. Со-но, типизировать стейт уже не нужно

2023-02-24 08:44 UTC, Kosurij commented on packages/client/src/pages/Settings/Settings.tsx
> +  object-position: -30px -121px;
Мб попробуем выровнять с помощью контейнеров и флексов? По идеи, достаточно будет накинуть стилей в `Row` (`align-items: center)`. 

ИМХО, так будет ровнее
![example](https://user-images.githubusercontent.com/62155518/221133056-14ee4d83-23ff-48a9-adab-16ca78042a1e.png)

2023-02-24 08:44 UTC, Kosurij commented on packages/client/src/pages/Settings/Settings.tsx
> +            <div>
А зачем ты все оборачиваешь в дивы? 

У всех этих элементов и так блочное отображение `(display: block)`, только у img `display: inline-block`.

Можно попробовать так 
```
<Button variant="primary" type="submit" onClick={onLeft}>
     ◀︎
</Button>
<Img src={sprite.sprite} />
<Button variant="primary" type="submit" onClick={onRight}>
     ▶︎
</Button>
```

2023-02-24 08:44 UTC, Kosurij commented on packages/client/src/pages/Settings/Settings.tsx
> +const LeaderboardComponent = styled.div`
Подскажи плиз, а почему он называется лидерборд, если это настройки?

2023-02-24 08:46 UTC, Kosurij requested changes

2023-02-24 08:46 UTC, Kosurij commented on packages/client/src/pages/Settings/Settings.tsx
> +  flex-direction: row;
Этот стиль стоит по умолчанию во флексе, можно не писать) На твое усмотрение

2023-02-24 08:48 UTC, m0000Amir commented on packages/client/src/pages/Settings/Settings.tsx
> +const LeaderboardComponent = styled.div`
Мой косяк, исправлю

2023-02-25 05:19 UTC, KomAnw approved these changes
Кажись после исправлений можно мержить)

2023-02-27 10:26 UTC, m0000Amir commented
C типами проблема при использовании наших `useAppSelector` и `useAppDispatch`. В следующем PR сделаю и тут подправлю.

2023-02-27 10:44 UTC, Kosurij approved these changes

2023-02-27 19:39 UTC, arudenko-offcl approved these changes
👌

2023-02-27 21:53 UTC, merged