Feature/225 45 local storage
KomAnw/whynot pull request #54
Opened 2023-03-12 17:50 UTC by MikhailSamigullin

### Cохранение данных в заполняемых формах в localStoreage
Данные сохраняются для формы изменения данных пользователя и регистрации.

### Скриншоты
#### Заходим в Profile edit
![Screenshot from 2023-03-12 21-22-06](https://user-images.githubusercontent.com/109307026/224562396-0738d000-3163-4cdb-a0d3-4cd09e99e320.png)

#### Редактируем данные, но не сохраняем
![Screenshot from 2023-03-12 21-22-42](https://user-images.githubusercontent.com/109307026/224562395-714cc216-d3f8-40ff-ae77-58b2572bee53.png)

#### Выходим со страницы, потом возвращаемся, и данные подгружаются из localStoreage
![Screenshot from 2023-03-12 21-22-49](https://user-images.githubusercontent.com/109307026/224562392-cb9618c0-be9c-43aa-ad9b-9a35ab8f4d33.png)

#### При отправке формы, данные из localStoreage удаляются
![Screenshot from 2023-03-12 21-23-30](https://user-images.githubusercontent.com/109307026/224562390-a66c6998-0eb1-4b12-ba15-f907f6c43f69.png)

2023-03-12 17:51 UTC, MikhailSamigullin commented on packages/client/src/components/Forms/ProfileData/ProfileData.tsx
> +  const saveToLocalStorage = (e: any) => {
вот тут any, не смог типизировать нормально

2023-03-12 17:52 UTC, MikhailSamigullin commented on packages/client/src/components/Forms/ProfileData/ProfileData.tsx
> +    <Form onSubmit={handleSubmit(submitForm)} onChange={(e: any) => saveToLocalStorage(e)}>
здесь тоже any

2023-03-13 07:51 UTC, Kosurij requested changes

2023-03-13 13:22 UTC, Kosurij approved these changes

2023-03-13 15:37 UTC, arudenko-offcl requested changes
Не забывай звать меня на ревью плиз 🙂 

Зареджектил, чтобы не вмержили, пока я посмотрю код, не пугайся )

2023-03-13 15:42 UTC, arudenko-offcl commented on packages/client/src/components/Forms/Registration/Registration.tsx
> +  });
А почему не передаешь их как defaultValues в useForm ?  Есть какой-то особенный смысл переназначать в useDidMount? 🤔

2023-03-13 15:44 UTC, arudenko-offcl commented on packages/client/src/components/Forms/Registration/Registration.tsx
> +  };
Лишняя обертка, можно сразу передавать saveToLocalStorage в `onChange={saveToLocalStorage}`

Другое дело, что saveToLocalStorage лучше бы быть просто функцией, которая берет ключ и значение и сеттит его в LS. А вот очищать о лишних данных объекта события лучше как раз в onChangeHandler.

2023-03-13 15:51 UTC, arudenko-offcl commented on packages/client/src/utils/storage.ts
> +export const setValueFromLocalStorageToField = (fields: TypeFormsConst[], setValue: UseFormSetValue<any>) => {
Хорошая практика стараться избегать использования any. 
В данном случае setValue можно типизировать так: 
`setValue: (key: string, value: string) => void`

Поскольку getItem() вернет либо null либо строку, то этого достаточно будет в данном случае.

2023-03-13 15:52 UTC, arudenko-offcl commented on packages/client/src/utils/storage.ts
> +  if (!isPasswordField(name)) {
Если передавать сюда только ключи и значение, то такие проверки не потребуются. Пусть функция отвечает лишь за установку данных в LS, а не определение того, что это за поле такое. Эту логику следует сделать вне )

2023-03-13 16:39 UTC, Kosurij commented on packages/client/src/utils/storage.ts
> +export const setValueFromLocalStorageToField = (fields: TypeFormsConst[], setValue: UseFormSetValue<any>) => {
Я тоже так думал, но нет (

![image](https://user-images.githubusercontent.com/62155518/224767853-1f573c56-f503-46cd-b212-86a94730b745.png)

2023-03-13 16:42 UTC, Kosurij commented on packages/client/src/utils/storage.ts
> +  if (!isPasswordField(name)) {
В таком случае, у нас получается просто лишняя обертка над `localStorage.setItem(name, value)`

2023-03-13 16:58 UTC, Kosurij commented on packages/client/src/components/Forms/Registration/Registration.tsx
> +  });
Есть, т.к. мы прокидываем туда setValue) Иначе получим ошибку, т.к. пытаемся прокинуть setValue до его инициализации

2023-03-13 17:44 UTC, KomAnw commented on packages/client/src/utils/storage.ts
> +export const setValueFromLocalStorageToField = (fields: TypeFormsConst[], setValue: UseFormSetValue<any>) => {
@arudenko-offcl мы уже в каком-то мре писали тебе ответ, что react-hook-form плохо типизирует эту функцию. Мы не нашли вариант того, как это сделать не через any, если ты можешь запустить наш проект и показать как это сделать - будем рады :)

2023-03-13 18:29 UTC, Kosurij commented on packages/client/src/utils/storage.ts
> +export const setValueFromLocalStorageToField = (fields: TypeFormsConst[], setValue: UseFormSetValue<any>) => {
Я с этого начал, но так не завелось. Мб ты глянешь? Т.к. я в тупике, получается очень много ненужных приседаний с типами.

![image](https://user-images.githubusercontent.com/62155518/224794087-9300001e-3eb7-4143-bdbc-afca6f3b1490.png)


![image](https://user-images.githubusercontent.com/62155518/224794870-5e5896af-2bc8-4016-8f7c-5e2863f85df6.png)

Казалось бы дело в литеральных ключах, но нет. Проблема в том, что он ждет тип `UseFormSetValue<TChangeProfileRequest>`. И дальше можно долго и упорно мучиться с проблемой этого типа, но я уже хз как это решить, а главное это не прям чтобы нужно.

Здесь же нам нужно просто использовать функцию `setValue` из этого пакета, со-но взять следует взять тип, который предлагают разрабы либы - `UseFormSetValue`, а он требует обязательный тип в дженерике. 

Просто добавить свой дженерик нельзя
![image](https://user-images.githubusercontent.com/62155518/224795909-e0657a8e-b916-4c38-9c98-898f46b36003.png)

Можно расширить тип, но тогда будет новая ошибка
![image](https://user-images.githubusercontent.com/62155518/224795991-37d68767-12c0-4459-a420-2c4bd1e9cfb8.png)

И вот тут я встаю в тупик.

При этом, тип прекрасно выводится сам и без типизации.
![image](https://user-images.githubusercontent.com/62155518/224795334-bac7f998-8f1b-41b5-aa72-f701952b3983.png)

2023-03-15 06:47 UTC, arudenko-offcl commented on packages/client/src/components/Forms/Registration/Registration.tsx
> +  });
Можно взять нзачения из LS и передать их в useForm в качестве defaultValues. Тогда не придется передавать setValue в функцию. Я об этом

2023-03-15 06:48 UTC, arudenko-offcl commented on packages/client/src/utils/storage.ts
> +export const setValueFromLocalStorageToField = (fields: TypeFormsConst[], setValue: UseFormSetValue<any>) => {
Смотрю, скоро отвечу

2023-03-15 06:49 UTC, arudenko-offcl commented on packages/client/src/utils/storage.ts
> +  if (!isPasswordField(name)) {
Ну да, получится что даже обертка не будет нужна в таком случае.

2023-03-15 07:25 UTC, arudenko-offcl commented on packages/client/src/utils/storage.ts
> +export const setValueFromLocalStorageToField = (fields: TypeFormsConst[], setValue: UseFormSetValue<any>) => {
Ну да, получается, что надо хорошо все обмазать дженериками на уровне `TypeFormsConst`  или стайпкастить тк из LS все равно приходят стринги в value. 

У меня вроде получилось стайпкастить, но так себе решение на самом деле )
<img width="603" alt="Screenshot 2023-03-15 at 09 20 58" src="https://user-images.githubusercontent.com/119289055/225235871-23ebc416-3ca8-4ea1-aab7-dabb5f040e91.png">

Энивей, думаю, можно в таком случае оставить фny, отзываю претензию ))

НО! Мне не нравится решение, при котором мы усложняем передачу значений из LS в useForm таким образом.

Что удмаете насчет того, чтобы полуить значения из LS на уровнеи компонента и передавать их как defaultValue в хук формы?

2023-03-15 07:28 UTC, arudenko-offcl reviewed
Почему бы не избавиться от `setValueFromLocalStorageToField` в пользу получения данных из LocalStorage и подкладывания их в useForm как defaultValues? Что думаешь ?

2023-03-15 12:17 UTC, Kosurij commented
> Почему бы не избавиться от `setValueFromLocalStorageToField` в пользу получения данных из LocalStorage и подкладывания их в useForm как defaultValues? Что думаешь ?

@arudenko-offcl 

Чекни плиз. Отказался от импорта setValue в пользу defaultValues. Утилки со-но тоже скорректировал. Проверка на поле пароля проходит в onChangeHandler

2023-03-16 10:47 UTC, Kosurij commented
@arudenko-offcl 

Ping

2023-03-16 12:24 UTC, merged