Feature/225 25 leaderboard api
KomAnw/whynot pull request #56
Opened 2023-03-16 00:12 UTC by m0000Amir

### Добавил `Leaderboard API`

 - само `API`;
 - добавил отрисовку на страницу `leaderboard`;
 - добавил запись `score` в бэк при завершении игры.

2023-03-16 06:34 UTC, Kosurij requested changes

2023-03-16 06:34 UTC, Kosurij commented on packages/client/src/api/leaderboard/leaderboard.ts
> +  add: ROOT_LEADERBOARD_URL,
Давай потом заменим на экземпляры URL, как тут - https://github.com/KomAnw/whynot/pull/55/files

2023-03-16 06:34 UTC, Kosurij commented on packages/client/src/api/leaderboard/leaderboard.ts
> +  return response.status === 200 ? response.json() : response.text();
У тебя ведь 2 из 3 эндпоинтов при статусе 200 возвращают текст 'ОК', и только последний эндпоинт - json

2023-03-16 06:34 UTC, Kosurij commented on packages/client/src/api/leaderboard/leaderboard.ts
> +          responseHandler: jsonTextResponseHandler,
Тут можно сделать так `responseHandler: 'text'`

2023-03-16 06:34 UTC, Kosurij commented on packages/client/src/api/leaderboard/leaderboard.ts
> +          responseHandler: jsonTextResponseHandler,
А тут вообще ничего не указывать, т.к. по умолчанию json стоит

2023-03-16 06:34 UTC, Kosurij commented on packages/client/src/api/leaderboard/leaderboard.ts
> +    add: build.mutation<AddNewLeaderResponse, LeaderboardNewLeaderRequest>({
Вместо AddNewLeaderResponse можно просто string указать

2023-03-16 06:34 UTC, Kosurij commented on packages/client/src/api/leaderboard/models.ts
> +  reason?: string;
Этот кейс подходит только для 400 статуса, я бы пока вообще не закладывался на отрицательные ответы. Можем сделать такую типизацию и информирование пользователя, если вернулась ошибка, в рамках другой таски

2023-03-16 06:34 UTC, Kosurij commented on packages/client/src/api/leaderboard/models.ts
> +  data: {
Тут точно нужна data?
Так нельзя?
```
{
    score: number;
    user_id: number;
    first_name: string;
};
```

2023-03-16 06:34 UTC, Kosurij commented on packages/client/src/components/App/constants.ts
> +export const LEADERBOARD_TEAM_NAME = 'wn';
Давай будем держать этот в `leaderboard.ts` рядом с `ROOT_LEADERBOARD_URL`? Это ведь относится только к апи лидерборда и в других местах будет не нужно

2023-03-16 06:34 UTC, Kosurij commented on packages/client/src/components/LeaderboardRow/LeaderboardRow.tsx
> +  // debugger
Забыл убрать

2023-03-16 06:34 UTC, Kosurij commented on packages/client/src/api/leaderboard/leaderboard.ts
> +    getTeamLeaderboard: build.query<LeadersResponse[], LeaderboardRequest>({
Это mutaion, а не query

2023-03-16 06:34 UTC, Kosurij commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +  const { data } = useGetTeamLeaderboardQuery({
Соответственно тут тебе нужно будет описать хэндлер, который ты будешь вызывать при первом рендере.

Можешь глянуть как я сделал в `src/pages/OAuth/OAuth.tsx`

2023-03-16 06:34 UTC, Kosurij commented on packages/client/src/pages/Game/components/GameResult/GameResult.tsx
> +        user_id: user?.id,
У тебя тут ТС ругается на типизацию и отсутствующие зависимости в useEffect.

Тут лучше вообще отказаться от useEffect и сделать все с помощью Lazy и хэндлера, который ты будешь вызывать по окончании игры. Глянь как я сделал в `src/components/Forms/Login/Login.tsx`

2023-03-16 19:13 UTC, arudenko-offcl reviewed
Хорошие замечания у коллеги @Kosurij

2023-03-19 20:59 UTC, arudenko-offcl approved these changes
👌 LGTM

2023-03-20 05:49 UTC, Kosurij approved these changes

2023-03-20 05:53 UTC, merged