Feature/225 113 add more one browser api
KomAnw/whynot pull request #58
Opened 2023-03-16 07:47 UTC by MikhailSamigullin

### Добавляем gamepad api
Включить использование gamepad можно в настройках.

### Скриншоты
![Screenshot from 2023-03-16 11-18-22](https://user-images.githubusercontent.com/109307026/225546421-6ccda621-0586-41f1-b32e-10f728f04f21.png)

https://www.youtube.com/embed/HZFolrKrDvM

2023-03-16 17:22 UTC, Kosurij requested changes

2023-03-16 17:22 UTC, Kosurij commented on packages/client/src/pages/Game/Game.tsx
> +  const game = useRef(NaN);
Тут тоже нужно заменить на null и типизировать через дженерик

2023-03-16 19:18 UTC, arudenko-offcl reviewed
🔢

2023-03-16 19:18 UTC, arudenko-offcl commented on packages/client/src/pages/Game/Game.tsx
> +    window.addEventListener('gamepaddisconnected', onDisconnectedGamepadHandler);
А отписать от `gamepadconnected` тут не нужно ? 🤔 
И я не очень понял логику, почему мы тут подписываемся на отключение геймпада, уточни пожалуйста

2023-03-17 05:20 UTC, MikhailSamigullin commented on packages/client/src/pages/Game/Game.tsx
> +    window.addEventListener('gamepaddisconnected', onDisconnectedGamepadHandler);
Здесь ошибся при копировании. Должно быть removeEventListener

2023-03-17 05:21 UTC, MikhailSamigullin commented on packages/client/src/pages/Game/Game.tsx
> +    game.current = NaN;
Исправил

2023-03-17 05:22 UTC, MikhailSamigullin commented on packages/client/src/pages/Game/Game.tsx
> +  const onConnectedGamepadHandler = (e: { gamepad: { index: number } }) => {
Done!

2023-03-17 05:23 UTC, MikhailSamigullin commented on packages/client/src/pages/Game/Game.tsx
> +  const game = useRef(NaN);
Валиден ли такой вариант?

2023-03-17 05:25 UTC, MikhailSamigullin commented on packages/client/src/pages/Game/Game.tsx
> +  const game = useRef(NaN);
переименовал в gamepadIndex, это название лучше отражает предназначение этой переменной

2023-03-17 15:55 UTC, arudenko-offcl requested changes
Я все-таки реджектну, тк мне кажется, что есть очень подозрительное место с подпиской/отпиской, уточни плиз, что там происходит

2023-03-17 15:55 UTC, arudenko-offcl commented on packages/client/src/pages/Game/Game.tsx
> +  const isGamepad = useRef(gamepad);
А зачем тебе флажок в рефе? Почему не используешь то, что получил из селектора строкой выше?

2023-03-18 18:28 UTC, MikhailSamigullin commented on packages/client/src/pages/Game/Game.tsx
> +    window.removeEventListener('gamepaddisconnected', onDisconnectedGamepadHandler);
В начале несовсем правильно понял логику с обработчиками событий у gamepad api, разобрался. Поправили

2023-03-18 18:31 UTC, MikhailSamigullin commented on packages/client/src/pages/Game/Game.tsx
> +      gamepadController(gamepadIndex.current as number);
Переписали на классы, от этой конструкции пришлось отказаться, но прием отличный!

2023-03-18 18:32 UTC, MikhailSamigullin commented on packages/client/src/pages/Game/Game.tsx
> +  const isGamepad = useRef(gamepad);
Это был костыль, после введения классов стало не актуально. Удалили

2023-03-18 18:35 UTC, Kosurij approved these changes

2023-03-19 21:00 UTC, arudenko-offcl approved these changes

2023-03-20 05:49 UTC, merged