Feature/225 127 page forum
KomAnw/whynot pull request #65
Opened 2023-03-22 23:50 UTC by efes2002

### Какую задачу решаем
Создание верстки страниц: Форум(список тем), Тема (обсуждение конкретной темы)

### Скриншоты/видяшка (если есть)

![2023-03-23_02-49-05](https://user-images.githubusercontent.com/65197828/227063838-736b93fa-6551-4a16-84e3-bd8139c29e40.png)
![2023-03-23_02-47-38](https://user-images.githubusercontent.com/65197828/227063872-387f6d98-3c1b-4750-93b3-7bd6ddc8e508.png)

### TBD (если есть)

2023-03-23 06:12 UTC, Kosurij commented on packages/client/public/images/forum/icon3.svg
Давай назовем иконки более явно? Чтобы из кода было понятно, что мы вставляем в качестве картинки?

2023-03-23 06:12 UTC, Kosurij commented on packages/client/src/components/App/constants.ts
> +          septenary: '#FFFFFF',
Это норм, что sextuple и septenary - одинаковые? В дефолтной теме они разные

2023-03-23 06:12 UTC, Kosurij commented on packages/client/src/components/Forum/ForumPost/MessageElement/MessageElement.tsx
> +// eslint-disable-next-line camelcase
А зачем ты дизейблишь правило?

2023-03-23 06:12 UTC, Kosurij commented on packages/client/src/components/Input/Input.test.tsx
> +  it('renders <ForumPostsInput /> correctly', () => {
Инпут это же универсальная компонента, не привязанная к конкретной странице. Тут ничего менять не нужно

2023-03-23 06:12 UTC, Kosurij commented on packages/client/src/pages/Forum/pages/Forum/Forum.tsx
> +export const Container = styled.div`
Ты его где-то еще используешь? Если нет, то экспорт не нужен

2023-03-23 06:12 UTC, Kosurij commented on packages/client/src/pages/Forum/pages/Post/Post.tsx
> +export const Container = styled.div`
Аналогично.

2023-03-23 06:36 UTC, Kosurij commented on packages/client/src/components/Forum/ForumPost/ForumMessageInput/ForumMessageInput.tsx
> +import styled from 'styled-components';
ИМХО, т.к. все эти файлы относятся только к форуму, то я бы вынес их в одноименную папку в pages/forum

![image](https://user-images.githubusercontent.com/62155518/227119051-523c0e10-b4ba-47b8-a468-c3bb14ee1abc.png)

Т.е. стало бы так

![image](https://user-images.githubusercontent.com/62155518/227119327-23370c11-c4ff-4b95-83e6-8d6892f0f616.png)

На мой взгляд, мы так не засоряем папку с общими переиспользуемыми компонентами

2023-03-23 06:36 UTC, Kosurij commented on packages/client/src/components/Forum/ForumPosts/ForumPosts.tsx
> +const Containers = styled('div')`
Давай заменим на единственное число? Это же один контейнер

2023-03-23 06:36 UTC, Kosurij commented on packages/client/src/components/Forum/ForumPosts/ForumPosts.tsx
> +  margin: 14px 0 0 0;
Давай заменим на margin-top

2023-03-23 06:36 UTC, Kosurij commented on packages/client/src/components/Forum/ForumPosts/ForumPosts.tsx
> +    background-color: #a29f9f;
Нужно вынести цвет скроллбара в переменные темы

2023-03-23 06:36 UTC, Kosurij commented on packages/client/src/components/Forum/ForumPosts/ForumPosts.tsx
> +  margin: 0;
Тут и так 0, можно убрать

2023-03-23 11:46 UTC, Kosurij commented on packages/client/src/components/Forum/ForumPosts/PostElement/PostElement.tsx
> +const Icon = styled.img`
Где-то в скобочках, где-то через точечную нотацию) Давай приведем к единому стилю?

2023-03-23 11:46 UTC, Kosurij commented on packages/client/src/components/Forum/ForumPosts/PostElement/PostElement.tsx
> +  margin: 0 10px 0 0;
`margin-right: 10px`

2023-03-23 11:46 UTC, Kosurij commented on packages/client/src/components/Forum/ForumPosts/PostElement/PostElement.tsx
> +const PostElement = ({ id, author, title }: TPost) => {
Очень сложно получается. Мб сделать что-то подобное?
```
<Title>
        <Icon src={iconMessage} alt="icon message" />
        <Link to={`${forum.index}/${id}`}>{title}</Link>
        <Author> {author.first_name} {author.second_name} </Author>
</Title>
```

Я бы вообще отказался от `NameAuthor`

2023-03-23 11:46 UTC, Kosurij commented on packages/client/src/components/Forum/types.ts
> +import React from 'react';
Не нужный импорт

2023-03-23 11:46 UTC, Kosurij commented on packages/client/src/components/Forum/types.ts
> +  setIsOpenMenuEmojis: React.Dispatch<React.SetStateAction<boolean>>;
`(value: boolean) => void`

2023-03-23 11:46 UTC, Kosurij commented on packages/client/src/components/Forum/ForumPosts/ForumPostsInput/ForumPostsInput.tsx
> +const InputStyled = styled(LinkText).attrs({ as: 'input' })<InputHTMLAttributes<HTMLInputElement>>`
А зачем это? У тебя же есть компонент инпута. Лучше возьми ее и переопредели что тебе нужно

2023-03-23 11:46 UTC, Kosurij commented on packages/client/src/components/Forum/ForumPosts/ForumPostsInput/ForumPostsInput.tsx
> +  background-size: cover;
`hover` нужно добавить, чтобы кнопка смотрелась более живой)

2023-03-23 11:46 UTC, Kosurij commented on packages/client/src/components/Forum/ForumPosts/ForumPostsInput/ForumPostsInput.tsx
> +  inputPosts: string;
Это же один пост?

2023-03-23 11:46 UTC, Kosurij commented on packages/client/src/components/Forum/ForumPost/ForumMessageInput/ForumMessageInput.tsx
> +const InputStyled = styled(LinkText).attrs({ as: 'input' })<InputHTMLAttributes<HTMLInputElement>>`
Лучше используй инпут из components

2023-03-23 12:56 UTC, Kosurij requested changes

2023-03-23 12:56 UTC, Kosurij commented on packages/client/src/components/Forum/ForumPost/MenuEmojis/MenuEmojis.tsx
> +    console.log(idClickEmoji);
Можно убрать

2023-03-23 12:56 UTC, Kosurij commented on packages/client/src/components/Forum/ForumPost/MessageElement/MessageElement.tsx
> +      ? css`
padding-left: ${({ elementId }) => elementId && '12px'};

2023-03-23 12:56 UTC, Kosurij commented on packages/client/src/components/Forum/ForumPost/ForumMessageInput/ForumMessageInput.tsx
> +const Direction = styled('div')`
Тут лучше взять Text за основу, а не див

2023-03-23 21:53 UTC, efes2002 commented on packages/client/src/components/Input/Input.test.tsx
> +  it('renders <ForumPostsInput /> correctly', () => {
Это не я, я точно суда не лазил, это похоже волшебство ВебШторма

2023-03-23 22:32 UTC, efes2002 commented on packages/client/src/components/Forum/ForumPost/utils/SortMessage.tsx
> +import { TMessage } from 'components/Forum/types';
Предлагаю пока оставить, по крайне мере сейчас визуально можно видеть распределение сообщений. Удалить успеем всегда.

2023-03-23 22:56 UTC, efes2002 commented on packages/client/src/components/Forum/ForumPosts/PostElement/PostElement.tsx
> +const PostElement = ({ id, author, title }: TPost) => {
Согласен что сложно но это из за того что макеты для большой страницы отличаются от маленькой, один элемент скрывается,  и маленький макет сам по себе сложный, там четыре элемента и все они разные по оформлению, плюс верхний и нижние рады смещены друг от друга.
![2023-03-24_01-52-21](https://user-images.githubusercontent.com/65197828/227382472-5713c64b-1194-43e0-995a-9794deff6856.png)
![2023-03-24_01-54-11](https://user-images.githubusercontent.com/65197828/227382481-20c160c5-f796-4428-9996-2cec33e48ab8.png)

2023-03-23 22:58 UTC, efes2002 commented on packages/client/src/components/Forum/types.ts
> +import React from 'react';
если его удалить то вот это лезет: 
![2023-03-24_01-57-53](https://user-images.githubusercontent.com/65197828/227382888-441a1f2b-64b0-4f7f-90e6-da34ec5bf560.png)

2023-03-23 23:17 UTC, efes2002 commented on packages/client/src/components/Forum/ForumPost/ForumMessageInput/ForumMessageInput.tsx
> +const InputStyled = styled(LinkText).attrs({ as: 'input' })<InputHTMLAttributes<HTMLInputElement>>`
У меня нет валидации и дизайн у меня другой (дизайн в стандартном импуте у нас не переопределяется)

2023-03-24 06:59 UTC, arudenko-offcl reviewed
Солидное ревью)
Но с отключением правила еслинта я прям не понял, зачем так часто?

2023-03-24 06:59 UTC, arudenko-offcl commented on packages/client/src/pages/Forum/pages/ForumMessages/components/MessageElement/MessageElement.tsx
> +        {/* eslint-disable-next-line camelcase */}
Очень часто используетс отключение правила. 
Тут надо что-то делать. Либо отрубить его в конфиге, либо преписать согласно правилу.

2023-03-24 06:59 UTC, arudenko-offcl commented on packages/client/src/pages/Forum/pages/ForumMessages/components/ForumMessageInput/ForumMessageInput.tsx
> +      console.log(error);
Для ошибок лучше console.error

2023-03-24 11:25 UTC, Kosurij requested changes

2023-03-24 11:25 UTC, Kosurij commented on packages/client/src/pages/Forum/pages/ForumPosts/components/ForumPostsInput/ForumPostsInput.tsx
> +      // eslint-disable-next-line no-console
убрать

2023-03-26 18:06 UTC, arudenko-offcl commented
Линты попадали(

Нужна ли помощь ?

2023-03-27 04:46 UTC, Kosurij approved these changes

2023-03-27 05:18 UTC, merged