Feature/225 55 component button
KomAnw/whynot pull request #7
Opened 2023-02-05 17:00 UTC by MikhailSamigullin

### Добавляем компонент Button
В компонент нужно передавать атрибуты для стилизации и использования функционала.

Импорт:
`import { Button } from '../Button/Button';`

Использование в коде:
`<Button signInButton xxsmall onClick={() => console.log('Test')} type={submit}>SIGN IN</Button>`

#### Виды атрибутов
##### Стандартные
    type,
    onSubmit,
    onClick
##### Стилизация(изменение) цвета
    signInButton,
    mainButton,
    signUpButton,
    playButton
##### Размеры кнопок
    xxsmall,
    xsmall,
    small,
    medium,
    normal,
    large,
    xlarge,
    xxlarge,

#### Использование с темизацией
        `const light = {
      color: '#FFFFFF',
      background: '#000000',
      hoverBackground: '#888888',
    };
    
    const dark = {
      color: '#000000',
      background: '#FFFFFF',
      hoverBackground: '#888888',
    };`

`<div>

      <ThemeProvider theme={light}>
        <div style={{ margin: '2px', border: '2px solid grey', padding: '5px' }}>
          <div>Тема light, кнопка с атрибутом signInButton и xxsmall</div>
          <Button signInButton xxsmall>
            SIGN IN
          </Button>
        </div>
      </ThemeProvider>
      <ThemeProvider theme={dark}>
        <div style={{ margin: '2px', border: '2px solid grey', padding: '5px' }}>
          <div>Тема dark, кнопка с атрибутом signInButton и xxsmall</div>
          <Button signInButton xxsmall>
            SIGN IN
          </Button>
        </div>
      </ThemeProvider>
    </div>`

### Скриншоты
![Screenshot from 2023-02-05 19-52-47](https://user-images.githubusercontent.com/109307026/216832752-3d3ea466-326b-462c-b339-986e852a75b8.png)

Код:

     ` <ThemeProvider theme={light}>
        <div style={{ margin: '2px', border: '2px solid grey', padding: '5px' }}>
          <div>Тема light, кнопка без атрибутов</div>
          <Button>BUTTON</Button>
        </div>
        <div style={{ margin: '2px', border: '2px solid grey', padding: '5px' }}>
          <div>Тема light, кнопка с атрибутом signInButton и xxsmall</div>
          <Button signInButton xxsmall>
            SIGN IN
          </Button>
        </div>
        <div style={{ margin: '2px', border: '2px solid grey', padding: '5px' }}>
          <div>Тема light, кнопка с атрибутом signUpButton и xsmall</div>
          <Button signUpButton xsmall>
            SIGN UP
          </Button>
        </div>
        <div style={{ margin: '2px', border: '2px solid grey', padding: '5px' }}>
          <div>Тема light, кнопка с атрибутом mainButton и small</div>
          <Button mainButton small>
            PLAY
          </Button>
        </div>
        <div style={{ margin: '2px', border: '2px solid grey', padding: '5px' }}>
          <div>Тема light, кнопка с атрибутом playButton и medium</div>
          <Button playButton medium>
            PLAY
          </Button>
        </div>
      </ThemeProvider>
      <ThemeProvider theme={dark}>
        <div style={{ margin: '2px', border: '2px solid grey', padding: '5px' }}>
          <div>Тема dark, кнопка без атрибутов</div>
          <Button>BUTTON</Button>
        </div>
        <div style={{ margin: '2px', border: '2px solid grey', padding: '5px' }}>
          <div>Тема dark, кнопка с атрибутом signInButton и normal</div>
          <Button signInButton normal>
            SIGN IN
          </Button>
        </div>
        <div style={{ margin: '2px', border: '2px solid grey', padding: '5px' }}>
          <div>Тема dark, кнопка с атрибутом signUpButton и large</div>
          <Button signUpButton large>
            SIGN UP
          </Button>
        </div>
        <div style={{ margin: '2px', border: '2px solid grey', padding: '5px' }}>
          <div>Тема dark, кнопка с атрибутом mainButton и xlarge</div>
          <Button mainButton xlarge>
            PLAY
          </Button>
        </div>
        <div style={{ margin: '2px', border: '2px solid grey', padding: '5px' }}>
          <div>Тема dark, кнопка с атрибутом playButton и xxlarge</div>
          <Button playButton xxlarge onClick={() => console.log('123')}>
            PLAY
          </Button>
        </div>
      </ThemeProvider>
    </div>
  );
}`

Размеры и цвета кнопок взяты из дизайна, если что то поменяется, то нужно менять и в компоненте.

2023-02-05 17:20 UTC, MikhailSamigullin commented on packages/client/src/components/Button/Button.tsx
> +  background: ${props => (props.signInButton ? '#6C5BC3' : null)};
Не уверен, можно ли это написать лучше

2023-02-05 19:57 UTC, m0000Amir requested changes
Нужно замержить к себе в ветку последние изменения их `develop`.

p.s. Вчера тоже запушил к себе, не проверив. ☺️

2023-02-05 19:57 UTC, m0000Amir commented on packages/client/src/components/Button/Button.tsx
> +interface ButtonProps extends InputHTMLAttributes<HTMLButtonElement> {
Может быть использовать `type` вместо `interface`.

2023-02-05 19:57 UTC, m0000Amir commented on packages/client/src/components/Button/Button.tsx
> +  normal?: boolean;
- `signInButton`, я понимаю это стиль кнопки, который верстается на странице входа. Может их попробовать прокидывать в качестве пропсов в кнопку. Чтобы стиль кнопки хранился только на одной странице. Сейчас верстка кнопки по странице входа будет гулять по всем проекту сразу.
- На примере пропсов `small`, `medium` и `normal`. Они все опциональные.  Что будет, если их сразу все указать.

2023-02-05 21:10 UTC, arudenko-offcl requested changes
🥉 
 Давай немного причешем интерфейс компонента и уменьшим количество пропсов. 
После этого подумаем, как красивее написать стили) 

Подсказка: для типизации пропсов можно использовать  `union` или `enum`

2023-02-05 21:10 UTC, arudenko-offcl commented on packages/client/src/components/Button/Button.tsx
> +  normal?: boolean;
Тут необходимо завести проп `size` и передавать в него одно из значений )

2023-02-05 21:10 UTC, arudenko-offcl commented on packages/client/src/components/Button/Button.tsx
> +  playButton?: boolean;
Здесь нужно завести проп, скажем, `theme` и так же в него передавать тип отображения нужной кнопки )

2023-02-06 06:54 UTC, Kosurij requested changes

2023-02-06 06:54 UTC, Kosurij commented on packages/client/src/components/Button/Button.tsx
> +    xxlarge,
Все эти пропсы можно 
```
xxsmall,
    xsmall,
    small,
    medium,
    normal,
    large,
    xlarge,
    xxlarge,
```
схлопнуть в один - `size`.

Эти пропсы - 
```
  signInButton,
  mainButton,
  signUpButton,
```
Можно схлопнуть в один - `variant`.

Использование должно быть таки: `<Button size='small' variant='secondary'> Мой текст </Button>`

2023-02-06 06:54 UTC, Kosurij commented on packages/client/src/components/Button/Button.tsx
> +      Кнопка
Тут тебе нужно добавить пропсу {children}, чтобы была возможность пробрасывать текст/jsx элемент извне. 

https://ru.reactjs.org/docs/glossary.html#propschildren

2023-02-06 06:59 UTC, Kosurij requested changes

2023-02-06 06:59 UTC, Kosurij commented on packages/client/src/components/Button/Button.tsx
> +  background: ${props => (props.mainButton ? '#6AADD6' : null)};
Судя по дизайну, у нас будет всего 2 вида кнопок

![Снимок экрана_20230206_095826](https://user-images.githubusercontent.com/62155518/216904044-0cafcee9-4821-4e8e-81db-b74333319148.png)

2023-02-06 07:09 UTC, MikhailSamigullin commented on packages/client/src/components/Button/Button.tsx
> +  background: ${props => (props.mainButton ? '#6AADD6' : null)};
Если так, то это сильно уменьшает варианты

2023-02-06 12:39 UTC, MikhailSamigullin commented on packages/client/src/components/Button/Button.tsx
> +  normal?: boolean;
Немного переработали логику под новый дизайн

2023-02-06 12:41 UTC, MikhailSamigullin commented on packages/client/src/components/Button/Button.tsx
> +    xxlarge,
от size отказался, т.к. в дизайне сейчас только один размер. 
variant='secondary'  - работает.

2023-02-06 12:41 UTC, MikhailSamigullin commented on packages/client/src/components/Button/Button.tsx
> +      Кнопка
Done!

2023-02-07 01:31 UTC, KomAnw reviewed
Осталось чутка поправить, остальное ок на мой взгляд

2023-02-07 01:31 UTC, KomAnw commented on packages/client/src/components/Button/Button.tsx
> +  font-size: ${({ theme, variant }) => theme[variant].button.fontSize || '32px'};
size не будет приходить из theme, нужно тут захардкодить

2023-02-07 01:31 UTC, KomAnw commented on packages/client/src/components/Button/types.ts
> +  theme?: any;
theme не будет пропом, она доступна внутри любого styled-component

2023-02-07 01:31 UTC, KomAnw commented on packages/client/src/components/Button/Button.tsx
> +export const Button = ({ type, theme, variant = 'primary', children, onSubmit, onClick }: ButtonComponent) => {
theme нужно убрать, она доступна внутри любого styled-component

2023-02-07 01:31 UTC, KomAnw commented on packages/client/src/components/Button/Button.tsx
> +  color: ${({ theme, variant }) => theme[variant].button.color || 'black'};
стяни develop к себе еще раз, там обновилась theme

2023-02-07 08:47 UTC, Kosurij commented on packages/client/src/components/Button/Button.tsx
> +  font-size: ${({ theme, variant }) => theme[variant].button.fontSize || '32px'};
Лучше сделать size таким же пропсом, как и variant. 

Можно что-нибудь подобное сделать с size.

![image](https://user-images.githubusercontent.com/62155518/217194877-bdc890f4-d8fd-490e-8f19-52050bf6e491.png)

2023-02-07 08:47 UTC, Kosurij commented on packages/client/src/components/Button/types.ts
> +  children: ReactNode | string;
Можно оставить только ReactNode. Он включает в себя string

2023-02-07 20:32 UTC, arudenko-offcl commented on packages/client/src/components/App/App.tsx
> +          <Route path="/game" element={<PrivateRoute />}>
Здесь path в константу забыл вынести.

И кажется, до приватных роутов мы не дойдем, попав на * )

2023-02-07 20:32 UTC, arudenko-offcl commented on packages/client/src/components/App/constants.ts
> +export const paths = {
Слушай, а расскажи, в чем идея тут и ниже в breakpoints использовать as const?
Почему не обойтись enum например ?

2023-02-07 20:32 UTC, arudenko-offcl commented on packages/client/src/components/Button/types.ts
> +export type ButtonComponent = ButtonProps & HTMLButtonElement;
Я предлагаю для таких кейсов обратить внимание на такой подход: 
https://react-typescript-cheatsheet.netlify.app/docs/advanced/patterns_by_usecase/#wrappingmirroring-a-html-element

2023-02-07 20:32 UTC, arudenko-offcl commented on packages/client/src/components/Switch/Switch.tsx
> +  const themeHandler = () => dispatch(changeTheme());
Лучше методы называть глаголами
Так же, есть хорошее правило, которое предлагаю вам с командой обсудить – называть коллбеки обработчиков событий с приставкой handle-
В данном случае, handleClick например

2023-02-07 20:32 UTC, arudenko-offcl commented on packages/client/src/hoc/ThemeWrapper/ThemeWrapper.tsx
> +const ThemeWrapper = ({ children }: ThemeWrapperProps) => {
Здесь нужно типизировать компонент как React.FC, а не типизировать пропсы

2023-02-07 20:32 UTC, arudenko-offcl commented on packages/client/src/hoc/ThemeWrapper/ThemeWrapper.tsx
> +const ThemeWrapper = ({ children }: ThemeWrapperProps) => {
Кроме того, предлагаю в команде обсудить, хотите ли вы для каждого компонента уносить типы пропсов в ./types

Очень субъективно, но как будто бы практика показывает, что их удобнее хранить рядом с компонентом

2023-02-07 20:46 UTC, KomAnw commented on packages/client/src/components/Button/types.ts
> +export type ButtonComponent = ButtonProps & HTMLButtonElement;
Не очень понятно что ты имеешь ввиду, мы с командой договорились type > interface

2023-02-07 20:47 UTC, KomAnw commented on packages/client/src/components/App/constants.ts
> +export const paths = {
По поводу enum: https://habr.com/ru/company/vk/blog/646789/

По поводу as const, посмотри он делает readonly каждое значение явно

2023-02-07 20:52 UTC, KomAnw commented on packages/client/src/hoc/ThemeWrapper/ThemeWrapper.tsx
> +const ThemeWrapper = ({ children }: ThemeWrapperProps) => {
По поводу FC, с командой договорились типизировать пропсы, а не компоненты, это два разных подхода и в обществе более предпочтимым является как раз таки типизация пропсов, а не компонентов.
Потому что если ты типизируешь один компонент - тебе нужно типизировать все, даже те, в которых нет никаких пропов

2023-02-07 21:03 UTC, KomAnw commented on packages/client/src/components/App/App.tsx
> +          <Route path="/game" element={<PrivateRoute />}>
Все гуд, дойдем, проверено.* перехватывает любое несовпадение по всем роутам

2023-02-08 20:12 UTC, Kosurij approved these changes

2023-02-08 20:12 UTC, Kosurij commented on .gitignore
>  .idea
Проверь плиз этот файл, .`editorconfig` и `.eslintignore`, чтобы они был как в девелопе.

Потому что ты каким-то образом затащил изменения из .github, а этого быть не должно. Она стоит в гитигноре

2023-02-08 20:12 UTC, Kosurij commented on packages/client/src/components/Button/index.ts
> +export { Button } from './Button';
Кстати, мб правда стоит подумать о том, чтобы размещать компоненты сразу в файле index.tsx

2023-02-08 20:56 UTC, m0000Amir approved these changes

2023-02-08 22:59 UTC, KomAnw commented on packages/client/src/components/Button/index.ts
> +export { Button } from './Button';
Я честно сказать противник этого, это действительно ужасно когдау тебя в трее открыто 5-6 вкладок index.tsx и ты не с первого раза можешь найти файл

2023-02-08 23:17 UTC, KomAnw commented
Мне кажется тут все окей

2023-02-08 23:17 UTC, merged