Feature/225 150 controller router post
KomAnw/whynot pull request #78
Opened 2023-04-01 00:03 UTC by efes2002

### Какую задачу решаем
Созданы Роуты и Контролеры для Постов

### Скриншоты/видяшка (если есть)
![2023-04-01_02-59-44](https://user-images.githubusercontent.com/65197828/229253455-ccda94e4-d86b-48dd-a4ca-cb5eb660bf33.png)

![2023-04-01_03-02-01](https://user-images.githubusercontent.com/65197828/229253988-f089fc83-03c1-4daf-9d61-221d6083a122.png)

### TBD (если есть)

2023-04-01 10:50 UTC, Kosurij commented on packages/server/package.json
> +    "celebrate": "^15.0.1",
Давай зафиксируем версию

2023-04-01 10:50 UTC, Kosurij commented on packages/server/routes/index.ts
> +routerApi.use('/posts', routerPosts);
Давай создадим отдельную папку под роуты форума?

2023-04-01 10:50 UTC, Kosurij commented on packages/server/routes/posts.ts
> +export const router = Router();
Можно импортировать из индекса

2023-04-01 10:50 UTC, Kosurij commented on packages/server/controllers/posts.ts
> +    PostModel.findAll().then(data => {
Давай все сделаем через async/await 

![image](https://user-images.githubusercontent.com/62155518/229284428-b351b635-fa53-487f-8336-6a5416cead70.png)

2023-04-02 18:09 UTC, Kosurij requested changes

2023-04-02 18:09 UTC, Kosurij commented on packages/server/src/app.ts
> +app.use(errors());
Тут немного нужно будет переиграть схему работы после залития этого ПР - https://github.com/KomAnw/whynot/pull/79

2023-04-02 18:09 UTC, Kosurij commented on packages/server/src/app.ts
> +app.use(bodyParser.json());
Тоже нужно будет вынести в мидлвару, как тут - https://github.com/KomAnw/whynot/pull/79

2023-04-02 18:09 UTC, Kosurij commented on packages/server/routes/posts/posts.ts
> +export const router = Router();
А разве не лучше создать общий экземпляр? Разве нельзя это сделать в routes/index.ts и импортировать его сюда? Или так не заведется?

2023-04-02 18:09 UTC, Kosurij commented on packages/server/middlewares/error.ts
> +const errorBadRequest = (_req: Request, res: Response) => {
Лучше назвать `notFoundMiddleware`. Тут все же не ошибка, а 404 код - ресурс не найден)

2023-04-02 18:09 UTC, Kosurij commented on packages/server/routes/index.ts
> +export const routerApi = Router();
Ты его импортируешь, а в постах используешь еще один экземпляр роутера. Можем стоит сделать router синглтоном?

2023-04-02 18:59 UTC, efes2002 commented on packages/server/routes/posts/posts.ts
> +export const router = Router();
Пробовал не работает, все падает, нам нужно его использовать в разных файлах и у роутов очень важна очередность подключения, а если мы его импортируем и потом клонируем и потом экспортируем  то при сборке не сойдется очередность. будет круговорот роутов. Это мои предположения почему не работает с одним роутом.

2023-04-02 19:02 UTC, Kosurij commented on packages/server/routes/posts/posts.ts
> +export const router = Router();
![image](https://user-images.githubusercontent.com/62155518/229373399-30507c45-174b-4319-8b51-51f31770aaf5.png)

2023-04-03 17:03 UTC, merged