Feature/225 71 theme
KomAnw/whynot pull request #8
Opened 2023-02-05 20:02 UTC by KomAnw

Обернул приложение в провайдер темы, сам провайдер это HOC, который подключен к слайсу redux, создал хранилище redux, создал компонент switch, пока что просто взял первый попавшийся

![image](https://user-images.githubusercontent.com/49876296/216841918-8173027a-04aa-4bcd-bd22-286476e9083b.png)

2023-02-05 20:14 UTC, m0000Amir approved these changes

2023-02-05 21:14 UTC, arudenko-offcl requested changes
Привет, не пугайся, я начал смотреть, но хочу закончить завтра. 

Пока поставлю реджект, но он ненастоящий, а временный, чтобы ПР случайно не влился, пока я смотрю )

2023-02-06 13:36 UTC, Kosurij approved these changes

2023-02-06 13:36 UTC, Kosurij commented on packages/client/src/store/store.ts
> +// Infer the `RootState` and `AppDispatch` types from the store itself
Мб убрать комменты?

2023-02-06 16:12 UTC, KomAnw commented on packages/client/src/store/store.ts
> +// Infer the `RootState` and `AppDispatch` types from the store itself
Да, можно конечно :)

2023-02-06 16:43 UTC, MikhailSamigullin approved these changes

2023-02-07 01:17 UTC, KomAnw commented
Прошло больше 24 часов, дожидаться ревью не стал, этот мр нужен для дальнейшей работы, смысла ждать нет.

2023-02-07 01:17 UTC, merged