Feature/225 157 theme api client
KomAnw/whynot pull request #89
Opened 2023-04-05 18:22 UTC by MikhailSamigullin

### Добавляем API получения theme и mode
+ внезапно понадобилось разделить логику на сервере для theme и mode
+ добавить новые ручки на обновление данных в БД

2023-04-05 18:27 UTC, m0000Amir approved these changes

2023-04-05 18:27 UTC, m0000Amir commented on packages/client/src/hoc/ThemeWrapper/themeSlice.ts
> +      console.log(state.name);
тут осталось

2023-04-06 14:53 UTC, Kosurij requested changes

2023-04-06 14:53 UTC, Kosurij commented on packages/client/src/api/theme/theme.ts
> +    addTheme: build.mutation<string, ThemeRequest>({
Такое же предложение: оставить 2 эндпоинта)

2023-04-07 15:44 UTC, Kosurij approved these changes

2023-04-07 15:57 UTC, Kosurij commented
![example](https://user-images.githubusercontent.com/62155518/230639224-a8cde1d2-0f7f-4559-b510-de8ff25f80cf.gif)

2023-04-09 13:20 UTC, merged