225-146-1-connection-Api-and-pagePosts
KomAnw/whynot pull request #90
Opened 2023-04-06 21:26 UTC by efes2002

### Какую задачу решаем
Настройка связи Базы данных и страницы Постов 

### Скриншоты/видяшка (если есть)
![2023-04-07_00-23-28](https://user-images.githubusercontent.com/65197828/230496691-865790d6-e341-4729-a82c-5ed1037d6806.png)

### TBD (если есть)

2023-04-07 11:52 UTC, arudenko-offcl approved these changes
LGTM 🆗

2023-04-07 13:54 UTC, m0000Amir approved these changes

2023-04-07 19:21 UTC, Kosurij requested changes

2023-04-07 19:21 UTC, Kosurij commented on packages/client/src/pages/Forum/pages/ForumPosts/components/PostsInput/PostsInput.tsx
> +  const dispatch = useDispatch();
Используй AppDispatch, там сразу есть типизация

2023-04-07 19:21 UTC, Kosurij approved these changes

2023-04-08 18:55 UTC, KomAnw requested changes

2023-04-08 18:55 UTC, KomAnw commented on packages/client/src/api/forum/posts/posts.ts
> +  tagTypes: ['Posts'],
а какой смысл от этого тега?

Все было бы ок, если бы мы его еще в post запросе использовали, тогда это бы работало так: получаем данные => отправляем/обновляем данные => и т.к. есть тег пост автоматически рефетчится

2023-04-08 18:55 UTC, KomAnw commented on packages/client/src/pages/Forum/pages/ForumPosts/ForumPosts.tsx
> +  }, [refetch]);
А это ли не костыль из-за неправильных тегов?

2023-04-09 19:57 UTC, merged