Sprint 7-8
KomAnw/whynot pull request #92
Opened 2023-04-09 19:58 UTC by KomAnw

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-04-09 20:07 UTC, arudenko-offcl requested changes
Гайз, а почему вы ПРы мержите с незарезолвленными реквестами на изменения?
https://github.com/KomAnw/whynot/pull/90
https://github.com/KomAnw/whynot/pull/91

2023-04-10 11:29 UTC, KomAnw commented
> Гайз, а почему вы ПРы мержите с незарезолвленными реквестами на изменения? #90 #91

1) Потому что мы на звонках договариваемся кто проведет финальное ревью, в этом случае остальное подтверждение от членов команды не требуется.
2) 'changes required' - просто подсвечивает человеку что мр нужно доработать, и пока что мержить нельзя
3) по поводу твоих замечаний - учтем, человек доработает по этим ошибкам, спасибо что отписался. Основной поинт - не понятно когда ожидать твоего ревью. В данном случае оно было уже после мержа :)
![image](https://user-images.githubusercontent.com/49876296/230893340-7d0af67a-7b25-40db-a732-dafaf403ca63.png)

2023-04-11 18:58 UTC, arudenko-offcl approved these changes
Часть ПРов я видел, часть вы отревьювили самостоятельно.

2023-04-20 18:47 UTC, Kosurij approved these changes

2023-04-20 18:47 UTC, merged