Feature/225 169
KomAnw/whynot pull request #94
Opened 2023-04-10 07:06 UTC by MikhailSamigullin

### Добавляем memory leaks файл с описанием всех утечек на проекте

2023-04-10 08:14 UTC, Kosurij requested changes

2023-04-10 08:14 UTC, Kosurij commented on MEMORYLEAKS.md
> +Добавили фунционал по сбросу состояния игры и переработали инициализацию в начале игры.
Давай напишем как именно решили: использовали `cancelAnimationFrame` при анмаунте компонента?

2023-04-10 08:14 UTC, Kosurij commented on MEMORYLEAKS.md
> +Игра заканчивается, если игрок упал с платформы. В этот момент появляется табло с результом и кнопка запуска еще одной сессии игры.
```suggestion
Игра заканчивается, если игрок упал с платформы. В этот момент появляется модальное окно с результатом и кнопка "Начать игру заново".
```

2023-04-10 08:14 UTC, Kosurij commented on MEMORYLEAKS.md
> +Оптимизировали логику добавления по необходиимости.
Давай напишем как именно решили эту проблему? Тут надо глянуть как это реализовано в классе платформ

2023-04-10 08:41 UTC, m0000Amir commented on MEMORYLEAKS.md
> +Так же было заметно при 3-4 открытых вкладках с игрой.
Фактически, после завершения, игра продолжала работать в фоне. Метод `requestAnimationFrame` заметно нагружал процессор, что сказывалось на производительности компьютера. Незначительное количество перезапусков игры или наличие 3-4 открытых вкладок с игрой существенно снижало работу браузера.

_Можно так написать. Но это не критично._

2023-04-10 08:57 UTC, m0000Amir approved these changes

2023-04-11 19:01 UTC, arudenko-offcl approved these changes
Ок. Довольно популярной практикой является еще скрины до/после закинуть с чиселками/графиками по перфомансу, если получится

2023-04-12 07:12 UTC, MikhailSamigullin commented
> Ок. Довольно популярной практикой является еще скрины до/после закинуть с чиселками/графиками по перфомансу, если получится

Спасибо за идею!
Но, к сожалению, сейчас откатиться до состояния, которое было при утечках памяти, очень сложно. Это было в 5 или 6 спринте, а после мерджа в основную ветку, другие ветки были удалены.

2023-04-13 11:21 UTC, Kosurij approved these changes

2023-04-13 11:21 UTC, merged